"""cdsi

Revision ID: 012c1e641d3f
Revises: 837e4812ac2e
Create Date: 2026-06-03 19:48:49.819396

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '012c1e641d3f'
down_revision = '837e4812ac2e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cdsi_vall_clubs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('clasif_cdsi_vall_playoff',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('grupo', sa.String(length=50), nullable=True),
    sa.Column('equipo', sa.String(length=50), nullable=True),
    sa.Column('jugados', sa.Integer(), nullable=True),
    sa.Column('ganados', sa.Integer(), nullable=True),
    sa.Column('perdidos', sa.Integer(), nullable=True),
    sa.Column('puntos', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('jornadas_cdsi_vall',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('playoff_cdsi_vall',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('encuentros', sa.String(length=20), nullable=False),
    sa.Column('fecha', sa.String(length=20), nullable=True),
    sa.Column('hora', sa.String(length=10), nullable=True),
    sa.Column('local', sa.String(length=100), nullable=True),
    sa.Column('resultadoA', sa.String(length=10), nullable=True),
    sa.Column('resultadoB', sa.String(length=10), nullable=True),
    sa.Column('visitante', sa.String(length=100), nullable=True),
    sa.Column('orden', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cdsi_vall_partidos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('jornada_id', sa.Integer(), nullable=False),
    sa.Column('fecha', sa.String(length=20), nullable=True),
    sa.Column('hora', sa.String(length=20), nullable=True),
    sa.Column('local', sa.String(length=255), nullable=True),
    sa.Column('resultadoA', sa.String(length=120), nullable=True),
    sa.Column('resultadoB', sa.String(length=120), nullable=True),
    sa.Column('visitante', sa.String(length=255), nullable=True),
    sa.Column('orden', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['jornada_id'], ['jornadas_cdsi_vall.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('cdsi_vall_partidos')
    op.drop_table('playoff_cdsi_vall')
    op.drop_table('jornadas_cdsi_vall')
    op.drop_table('clasif_cdsi_vall_playoff')
    op.drop_table('cdsi_vall_clubs')
    # ### end Alembic commands ###
