"""el salvador

Revision ID: 06d6c720ac7e
Revises: 716deaa7e4f6
Create Date: 2026-05-31 19:42:41.837115

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '06d6c720ac7e'
down_revision = '716deaa7e4f6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clasificacion_euro_salvador',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('grupo', sa.String(length=50), nullable=True),
    sa.Column('equipo', sa.String(length=50), nullable=True),
    sa.Column('jugados', sa.Integer(), nullable=True),
    sa.Column('ganados', sa.Integer(), nullable=True),
    sa.Column('perdidos', sa.Integer(), nullable=True),
    sa.Column('puntos', sa.Integer(), nullable=True),
    sa.Column('bonus', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('copa_salvador',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('encuentros', sa.String(length=20), nullable=False),
    sa.Column('fecha', sa.String(length=20), nullable=True),
    sa.Column('hora', sa.String(length=10), nullable=True),
    sa.Column('local', sa.String(length=100), nullable=True),
    sa.Column('bonusA', sa.String(length=120), nullable=True),
    sa.Column('resultadoA', sa.String(length=10), nullable=True),
    sa.Column('resultadoB', sa.String(length=10), nullable=True),
    sa.Column('bonusB', sa.String(length=120), nullable=True),
    sa.Column('visitante', sa.String(length=100), nullable=True),
    sa.Column('orden', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('europa_salvador',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('encuentros', sa.String(length=20), nullable=False),
    sa.Column('fecha', sa.String(length=20), nullable=True),
    sa.Column('hora', sa.String(length=10), nullable=True),
    sa.Column('local', sa.String(length=100), nullable=True),
    sa.Column('bonusA', sa.String(length=120), nullable=True),
    sa.Column('resultadoA', sa.String(length=10), nullable=True),
    sa.Column('resultadoB', sa.String(length=10), nullable=True),
    sa.Column('bonusB', sa.String(length=120), nullable=True),
    sa.Column('visitante', sa.String(length=100), nullable=True),
    sa.Column('orden', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('jornadas_salvador',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fase', sa.String(length=20), nullable=True),
    sa.Column('nombre', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('playoff_salvador',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('eliminatoria', sa.String(length=20), nullable=False),
    sa.Column('fecha', sa.String(length=20), nullable=True),
    sa.Column('hora', sa.String(length=10), nullable=True),
    sa.Column('local', sa.String(length=100), nullable=True),
    sa.Column('bonusA', sa.String(length=120), nullable=True),
    sa.Column('resultadoA', sa.String(length=10), nullable=True),
    sa.Column('resultadoB', sa.String(length=10), nullable=True),
    sa.Column('bonusB', sa.String(length=120), nullable=True),
    sa.Column('visitante', sa.String(length=100), nullable=True),
    sa.Column('orden', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('salvador_clubs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('supercopa_iberica_salvador',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('eliminatoria', sa.String(length=20), nullable=False),
    sa.Column('fecha', sa.String(length=20), nullable=True),
    sa.Column('hora', sa.String(length=10), nullable=True),
    sa.Column('local', sa.String(length=100), nullable=True),
    sa.Column('bonusA', sa.String(length=120), nullable=True),
    sa.Column('resultadoA', sa.String(length=10), nullable=True),
    sa.Column('resultadoB', sa.String(length=10), nullable=True),
    sa.Column('bonusB', sa.String(length=120), nullable=True),
    sa.Column('visitante', sa.String(length=100), nullable=True),
    sa.Column('orden', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('salvador_partidos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('jornada_id', sa.Integer(), nullable=False),
    sa.Column('fecha', sa.String(length=20), nullable=True),
    sa.Column('hora', sa.String(length=20), nullable=True),
    sa.Column('local', sa.String(length=255), nullable=True),
    sa.Column('bonusA', sa.String(length=120), nullable=True),
    sa.Column('resultadoA', sa.String(length=120), nullable=True),
    sa.Column('resultadoB', sa.String(length=120), nullable=True),
    sa.Column('bonusB', sa.String(length=120), nullable=True),
    sa.Column('visitante', sa.String(length=255), nullable=True),
    sa.Column('orden', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['jornada_id'], ['jornadas_salvador.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('jornadas_vrac', schema=None) as batch_op:
        batch_op.alter_column('fase',
               existing_type=sa.VARCHAR(length=20),
               nullable=True,
               existing_server_default=sa.text("'regular'::character varying"))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('jornadas_vrac', schema=None) as batch_op:
        batch_op.alter_column('fase',
               existing_type=sa.VARCHAR(length=20),
               nullable=False,
               existing_server_default=sa.text("'regular'::character varying"))

    op.drop_table('salvador_partidos')
    op.drop_table('supercopa_iberica_salvador')
    op.drop_table('salvador_clubs')
    op.drop_table('playoff_salvador')
    op.drop_table('jornadas_salvador')
    op.drop_table('europa_salvador')
    op.drop_table('copa_salvador')
    op.drop_table('clasificacion_euro_salvador')
    # ### end Alembic commands ###
