"""aula

Revision ID: 0b99c2c27113
Revises: b04a763e76bb
Create Date: 2025-04-21 21:10:21.493395

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0b99c2c27113'
down_revision = 'b04a763e76bb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('supercopa_aula')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('supercopa_aula',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('eliminatoria', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('fecha', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('hora', sa.VARCHAR(length=10), autoincrement=False, nullable=True),
    sa.Column('local', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('resultadoA', sa.VARCHAR(length=10), autoincrement=False, nullable=True),
    sa.Column('resultadoB', sa.VARCHAR(length=10), autoincrement=False, nullable=True),
    sa.Column('visitante', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('orden', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='supercopa_aula_pkey')
    )
    # ### end Alembic commands ###
