"""cdsi

Revision ID: 0c0431cde3a2
Revises: b661e077aed4
Create Date: 2026-07-01 16:17:18.763398

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0c0431cde3a2'
down_revision = 'b661e077aed4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('temporadas_aliados',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=20), nullable=False),
    sa.Column('activa', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre')
    )
    op.create_table('temporadas_cdsi_vall',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=20), nullable=False),
    sa.Column('activa', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre')
    )
    op.create_table('temporadas_ponce',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=20), nullable=False),
    sa.Column('activa', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre')
    )
    with op.batch_alter_table('jornadas_aliados', schema=None) as batch_op:
        batch_op.add_column(sa.Column('temporada_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'temporadas_aliados', ['temporada_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('jornadas_cdsi_vall', schema=None) as batch_op:
        batch_op.add_column(sa.Column('temporada_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'temporadas_cdsi_vall', ['temporada_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('jornadas_ponce', schema=None) as batch_op:
        batch_op.add_column(sa.Column('temporada_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'temporadas_ponce', ['temporada_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('jornadas_ponce', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('temporada_id')

    with op.batch_alter_table('jornadas_cdsi_vall', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('temporada_id')

    with op.batch_alter_table('jornadas_aliados', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('temporada_id')

    op.drop_table('temporadas_ponce')
    op.drop_table('temporadas_cdsi_vall')
    op.drop_table('temporadas_aliados')
    # ### end Alembic commands ###
