"""encuentros

Revision ID: 16477e4a6c04
Revises: 925afca70235
Create Date: 2025-05-18 16:21:32.222209

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '16477e4a6c04'
down_revision = '925afca70235'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clasificacion_euro_caja',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('grupo', sa.String(length=50), nullable=True),
    sa.Column('equipo', sa.String(length=50), nullable=True),
    sa.Column('jugados', sa.Integer(), nullable=True),
    sa.Column('ganados', sa.Integer(), nullable=True),
    sa.Column('perdidos', sa.Integer(), nullable=True),
    sa.Column('puntos', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('europa_caja', schema=None) as batch_op:
        batch_op.add_column(sa.Column('encuentros', sa.String(length=20), nullable=False))
        batch_op.drop_column('eliminatoria')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('europa_caja', schema=None) as batch_op:
        batch_op.add_column(sa.Column('eliminatoria', sa.VARCHAR(length=20), autoincrement=False, nullable=False))
        batch_op.drop_column('encuentros')

    op.drop_table('clasificacion_euro_caja')
    # ### end Alembic commands ###
