"""aliados

Revision ID: 1e9478dff282
Revises: dd132aceebd8
Create Date: 2026-08-11 18:32:11.575533

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1e9478dff282'
down_revision = 'dd132aceebd8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('aliados_grupos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('temporada_id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=20), nullable=False),
    sa.Column('fase', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['temporada_id'], ['temporadas_aliados.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('aliados_grupos_equipos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('grupo_id', sa.Integer(), nullable=False),
    sa.Column('equipo', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['grupo_id'], ['aliados_grupos.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('aliados_grupos_equipos')
    op.drop_table('aliados_grupos')
    # ### end Alembic commands ###
