"""grupos

Revision ID: 234864163aaa
Revises: 1e9478dff282
Create Date: 2026-08-11 19:06:18.559869

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '234864163aaa'
down_revision = '1e9478dff282'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('aliados_grupos', schema=None) as batch_op:
        batch_op.drop_constraint('aliados_grupos_temporada_id_fkey', type_='foreignkey')
        batch_op.drop_column('temporada_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('aliados_grupos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('temporada_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.create_foreign_key('aliados_grupos_temporada_id_fkey', 'temporadas_aliados', ['temporada_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###
