"""uemc

Revision ID: 282b9818d3ff
Revises: 921adc37b5d0
Create Date: 2026-07-22 13:33:19.391846

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '282b9818d3ff'
down_revision = '921adc37b5d0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('copa_uemc', schema=None) as batch_op:
        batch_op.add_column(sa.Column('grupo', sa.String(length=10), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('copa_uemc', schema=None) as batch_op:
        batch_op.drop_column('grupo')

    # ### end Alembic commands ###
