"""salva

Revision ID: 2a43a12df4ae
Revises: 66336ae04e97
Create Date: 2026-07-01 18:20:54.749192

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2a43a12df4ae'
down_revision = '66336ae04e97'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('temporadas_salvador',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=20), nullable=False),
    sa.Column('activa', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre')
    )
    op.create_table('temporadas_salvador_fem',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=20), nullable=False),
    sa.Column('activa', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre')
    )
    op.create_table('temporadas_san_jose',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=20), nullable=False),
    sa.Column('activa', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre')
    )
    op.create_table('temporadas_vcv',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=20), nullable=False),
    sa.Column('activa', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre')
    )
    op.create_table('temporadas_vrac',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=20), nullable=False),
    sa.Column('activa', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre')
    )
    with op.batch_alter_table('jornadas_salvador', schema=None) as batch_op:
        batch_op.add_column(sa.Column('temporada_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'temporadas_salvador', ['temporada_id'], ['id'], ondelete='CASCADE')
        batch_op.drop_column('fase')

    with op.batch_alter_table('jornadas_salvador_fem', schema=None) as batch_op:
        batch_op.add_column(sa.Column('temporada_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'temporadas_salvador_fem', ['temporada_id'], ['id'], ondelete='CASCADE')
        batch_op.drop_column('fase')

    with op.batch_alter_table('jornadas_san_jose', schema=None) as batch_op:
        batch_op.add_column(sa.Column('temporada_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'temporadas_san_jose', ['temporada_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('jornadas_vcv', schema=None) as batch_op:
        batch_op.add_column(sa.Column('temporada_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'temporadas_vcv', ['temporada_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('jornadas_vrac', schema=None) as batch_op:
        batch_op.add_column(sa.Column('temporada_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'temporadas_vrac', ['temporada_id'], ['id'], ondelete='CASCADE')
        batch_op.drop_column('fase')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('jornadas_vrac', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fase', sa.VARCHAR(length=20), server_default=sa.text("'regular'::character varying"), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('temporada_id')

    with op.batch_alter_table('jornadas_vcv', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('temporada_id')

    with op.batch_alter_table('jornadas_san_jose', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('temporada_id')

    with op.batch_alter_table('jornadas_salvador_fem', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fase', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('temporada_id')

    with op.batch_alter_table('jornadas_salvador', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fase', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('temporada_id')

    op.drop_table('temporadas_vrac')
    op.drop_table('temporadas_vcv')
    op.drop_table('temporadas_san_jose')
    op.drop_table('temporadas_salvador_fem')
    op.drop_table('temporadas_salvador')
    # ### end Alembic commands ###
