"""histor

Revision ID: 2aaff7ccbbcc
Revises: 7e34b9a2dfdf
Create Date: 2026-07-13 19:42:36.285568

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2aaff7ccbbcc'
down_revision = '7e34b9a2dfdf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('palmares_promesas')
    op.drop_table('historial_uemc')
    op.drop_table('palmares_parquesol')
    op.drop_table('palmares_simancas')
    op.drop_table('palmares_uemc')
    op.drop_table('historial_promesas')
    op.drop_table('historial_parquesol')
    op.drop_table('historial_simancas')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('historial_simancas',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('temporada_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('liga', sa.VARCHAR(length=80), autoincrement=False, nullable=False),
    sa.Column('puntos', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('puesto', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('playoff', sa.VARCHAR(length=80), autoincrement=False, nullable=True),
    sa.Column('copa', sa.VARCHAR(length=80), autoincrement=False, nullable=True),
    sa.Column('titulos', sa.VARCHAR(length=150), autoincrement=False, nullable=True),
    sa.Column('siguiente_temporada', sa.VARCHAR(length=80), autoincrement=False, nullable=True),
    sa.Column('observaciones', sa.VARCHAR(length=200), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['temporada_id'], ['temporadas_simancas.id'], name='historial_simancas_temporada_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='historial_simancas_pkey')
    )
    op.create_table('historial_parquesol',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('temporada_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('liga', sa.VARCHAR(length=80), autoincrement=False, nullable=False),
    sa.Column('puntos', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('puesto', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('playoff', sa.VARCHAR(length=80), autoincrement=False, nullable=True),
    sa.Column('copa', sa.VARCHAR(length=80), autoincrement=False, nullable=True),
    sa.Column('titulos', sa.VARCHAR(length=150), autoincrement=False, nullable=True),
    sa.Column('siguiente_temporada', sa.VARCHAR(length=80), autoincrement=False, nullable=True),
    sa.Column('observaciones', sa.VARCHAR(length=200), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['temporada_id'], ['temporadas_parquesol.id'], name='historial_parquesol_temporada_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='historial_parquesol_pkey')
    )
    op.create_table('historial_promesas',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('temporada_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('liga', sa.VARCHAR(length=80), autoincrement=False, nullable=False),
    sa.Column('puntos', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('puesto', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('playoff', sa.VARCHAR(length=80), autoincrement=False, nullable=True),
    sa.Column('copa', sa.VARCHAR(length=80), autoincrement=False, nullable=True),
    sa.Column('titulos', sa.VARCHAR(length=150), autoincrement=False, nullable=True),
    sa.Column('siguiente_temporada', sa.VARCHAR(length=80), autoincrement=False, nullable=True),
    sa.Column('observaciones', sa.VARCHAR(length=200), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['temporada_id'], ['temporadas_promesas.id'], name='historial_promesas_temporada_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='historial_promesas_pkey')
    )
    op.create_table('palmares_uemc',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('temporada_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('competicion', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('imagen', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['temporada_id'], ['temporadas_uemc.id'], name='palmares_uemc_temporada_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='palmares_uemc_pkey')
    )
    op.create_table('palmares_simancas',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('temporada_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('competicion', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('imagen', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['temporada_id'], ['temporadas_simancas.id'], name='palmares_simancas_temporada_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='palmares_simancas_pkey')
    )
    op.create_table('palmares_parquesol',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('temporada_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('competicion', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('imagen', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['temporada_id'], ['temporadas_parquesol.id'], name='palmares_parquesol_temporada_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='palmares_parquesol_pkey')
    )
    op.create_table('historial_uemc',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('temporada_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('liga', sa.VARCHAR(length=80), autoincrement=False, nullable=False),
    sa.Column('puntos', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('puesto', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('playoff', sa.VARCHAR(length=80), autoincrement=False, nullable=True),
    sa.Column('copa', sa.VARCHAR(length=80), autoincrement=False, nullable=True),
    sa.Column('titulos', sa.VARCHAR(length=150), autoincrement=False, nullable=True),
    sa.Column('siguiente_temporada', sa.VARCHAR(length=80), autoincrement=False, nullable=True),
    sa.Column('observaciones', sa.VARCHAR(length=200), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['temporada_id'], ['temporadas_uemc.id'], name='historial_uemc_temporada_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='historial_uemc_pkey')
    )
    op.create_table('palmares_promesas',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('temporada_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('competicion', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('imagen', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['temporada_id'], ['temporadas_promesas.id'], name='palmares_promesas_temporada_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='palmares_promesas_pkey')
    )
    # ### end Alembic commands ###
