"""tabla clasificacion_copa

Revision ID: 302d3a4d0881
Revises: 12f4cc1e6c1e
Create Date: 2025-04-08 23:04:28.621573

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '302d3a4d0881'
down_revision = '12f4cc1e6c1e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clasificacion_copa',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('grupo', sa.String(length=50), nullable=True),
    sa.Column('equipo', sa.String(length=50), nullable=True),
    sa.Column('jugados', sa.Integer(), nullable=True),
    sa.Column('ganados', sa.Integer(), nullable=True),
    sa.Column('perdidos', sa.Integer(), nullable=True),
    sa.Column('puntos', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('clasificacion_copa')
    # ### end Alembic commands ###
