"""genius

Revision ID: 32fb096c3204
Revises: d365f46dcdd5
Create Date: 2026-08-19 23:42:40.762244

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '32fb096c3204'
down_revision = 'd365f46dcdd5'
branch_labels = None
depends_on = None


def upgrade():
    # Eliminar primero la tabla que depende de grupos
    op.drop_table('vallad_genius_grupos_equipos')

    # Después eliminar la tabla de grupos
    op.drop_table('vallad_genius_grupos')

    # Añadir puntos Fair Play a los partidos
    with op.batch_alter_table('vallad_genius_partidos', schema=None) as batch_op:
        batch_op.add_column(
            sa.Column('pfp_local', sa.Integer(), nullable=True)
        )
        batch_op.add_column(
            sa.Column('pfp_visitante', sa.Integer(), nullable=True)
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vallad_genius_partidos', schema=None) as batch_op:
        batch_op.drop_column('pfp_visitante')
        batch_op.drop_column('pfp_local')

    op.create_table('vallad_genius_grupos_equipos',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('grupo_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('equipo', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['grupo_id'], ['vallad_genius_grupos.id'], name='vallad_genius_grupos_equipos_grupo_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='vallad_genius_grupos_equipos_pkey')
    )
    op.create_table('vallad_genius_grupos',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('nombre', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('fase', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='vallad_genius_grupos_pkey')
    )
    # ### end Alembic commands ###
