"""modificacion

Revision ID: 34717cb20ca3
Revises: b7d5e925c528
Create Date: 2025-04-11 17:01:25.794414

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '34717cb20ca3'
down_revision = 'b7d5e925c528'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('promesas_partidos', schema=None) as batch_op:
        batch_op.alter_column('hora',
               existing_type=postgresql.TIME(),
               type_=sa.String(length=25),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('promesas_partidos', schema=None) as batch_op:
        batch_op.alter_column('hora',
               existing_type=sa.String(length=25),
               type_=postgresql.TIME(),
               nullable=False)

    # ### end Alembic commands ###
