"""clasif_ponce_playoff

Revision ID: 34acafb3aa71
Revises: ba11f38243c4
Create Date: 2026-01-23 13:15:21.479392

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '34acafb3aa71'
down_revision = 'ba11f38243c4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clasif_ponce_playoff',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('grupo', sa.String(length=50), nullable=True),
    sa.Column('equipo', sa.String(length=50), nullable=True),
    sa.Column('jugados', sa.Integer(), nullable=True),
    sa.Column('ganados', sa.Integer(), nullable=True),
    sa.Column('perdidos', sa.Integer(), nullable=True),
    sa.Column('puntos', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('clasif_ponce_playoff')
    # ### end Alembic commands ###
