"""fix temporadas

Revision ID: 353478d6159d
Revises: 7df8dd1633f8
Create Date: 2026-06-29 16:22:17.406539

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '353478d6159d'
down_revision = '7df8dd1633f8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('temporadas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=20), nullable=False),
    sa.Column('activa', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre')
    )
    with op.batch_alter_table('jornadas_valladolid', schema=None) as batch_op:
        batch_op.add_column(sa.Column('temporada_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'temporadas', ['temporada_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('jornadas_valladolid', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('temporada_id')

    op.drop_table('temporadas')
    # ### end Alembic commands ###
