"""vrac

Revision ID: 3a18173af5f2
Revises: 80de7ffb6990
Create Date: 2026-07-13 12:47:42.475847

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3a18173af5f2'
down_revision = '80de7ffb6990'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vrac_partidos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fase', sa.String(length=30), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vrac_partidos', schema=None) as batch_op:
        batch_op.drop_column('fase')

    # ### end Alembic commands ###
