"""eliminatoria

Revision ID: 3a533e0cb131
Revises: d937b23b59cc
Create Date: 2025-04-11 12:17:44.889200

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3a533e0cb131'
down_revision = 'd937b23b59cc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('copa_valladolid', schema=None) as batch_op:
        batch_op.add_column(sa.Column('eliminatoria', sa.String(length=50), nullable=False))
        batch_op.drop_column('encuentros')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('copa_valladolid', schema=None) as batch_op:
        batch_op.add_column(sa.Column('encuentros', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
        batch_op.drop_column('eliminatoria')

    # ### end Alembic commands ###
