"""prome

Revision ID: 3aad7652949b
Revises: b5091ba40f9f
Create Date: 2026-07-11 11:39:42.306353

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3aad7652949b'
down_revision = 'b5091ba40f9f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('historial_promesas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('temporada_id', sa.Integer(), nullable=False),
    sa.Column('liga', sa.String(length=80), nullable=False),
    sa.Column('puntos', sa.Integer(), nullable=True),
    sa.Column('puesto', sa.Integer(), nullable=True),
    sa.Column('playoff', sa.String(length=80), nullable=True),
    sa.Column('copa', sa.String(length=80), nullable=True),
    sa.Column('titulos', sa.String(length=150), nullable=True),
    sa.Column('siguiente_temporada', sa.String(length=80), nullable=True),
    sa.Column('observaciones', sa.String(length=200), nullable=True),
    sa.ForeignKeyConstraint(['temporada_id'], ['temporadas_promesas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('palmares_promesas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('temporada_id', sa.Integer(), nullable=False),
    sa.Column('competicion', sa.String(length=100), nullable=False),
    sa.Column('imagen', sa.String(length=100), nullable=False),
    sa.ForeignKeyConstraint(['temporada_id'], ['temporadas_promesas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('palmares_promesas')
    op.drop_table('historial_promesas')
    # ### end Alembic commands ###
