"""tabla uemc_clubs

Revision ID: 3ea9d07e0913
Revises: f81e6c3a1d49
Create Date: 2025-04-08 16:45:16.169027

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3ea9d07e0913'
down_revision = 'f81e6c3a1d49'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('uemc_clubs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('uemc_partidos', schema=None) as batch_op:
        batch_op.alter_column('resultadoA',
               existing_type=sa.VARCHAR(length=10),
               type_=sa.String(length=120),
               existing_nullable=True)
        batch_op.alter_column('resultadoB',
               existing_type=sa.VARCHAR(length=10),
               type_=sa.String(length=120),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('uemc_partidos', schema=None) as batch_op:
        batch_op.alter_column('resultadoB',
               existing_type=sa.String(length=120),
               type_=sa.VARCHAR(length=10),
               existing_nullable=True)
        batch_op.alter_column('resultadoA',
               existing_type=sa.String(length=120),
               type_=sa.VARCHAR(length=10),
               existing_nullable=True)

    op.drop_table('uemc_clubs')
    # ### end Alembic commands ###
