"""eliminatoria

Revision ID: 43bd3d304a36
Revises: 17d082253c6b
Create Date: 2025-05-20 20:38:11.243429

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '43bd3d304a36'
down_revision = '17d082253c6b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('copa_vrac', schema=None) as batch_op:
        batch_op.add_column(sa.Column('encuentros', sa.String(length=20), nullable=False))
        batch_op.drop_column('eliminatoria')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('copa_vrac', schema=None) as batch_op:
        batch_op.add_column(sa.Column('eliminatoria', sa.VARCHAR(length=20), autoincrement=False, nullable=False))
        batch_op.drop_column('encuentros')

    # ### end Alembic commands ###
