"""favor y contra

Revision ID: 4592a9542110
Revises: 63d43129d849
Create Date: 2026-05-15 19:43:00.275496

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4592a9542110'
down_revision = '63d43129d849'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('clasificacion_eurocup', schema=None) as batch_op:
        batch_op.add_column(sa.Column('favor', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('contra', sa.String(length=255), nullable=True))
        batch_op.alter_column('jugados',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=20),
               existing_nullable=True)
        batch_op.alter_column('ganados',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=20),
               existing_nullable=True)
        batch_op.alter_column('perdidos',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=20),
               existing_nullable=True)
        batch_op.alter_column('puntos',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=150),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('clasificacion_eurocup', schema=None) as batch_op:
        batch_op.alter_column('puntos',
               existing_type=sa.String(length=150),
               type_=sa.INTEGER(),
               existing_nullable=True)
        batch_op.alter_column('perdidos',
               existing_type=sa.String(length=20),
               type_=sa.INTEGER(),
               existing_nullable=True)
        batch_op.alter_column('ganados',
               existing_type=sa.String(length=20),
               type_=sa.INTEGER(),
               existing_nullable=True)
        batch_op.alter_column('jugados',
               existing_type=sa.String(length=20),
               type_=sa.INTEGER(),
               existing_nullable=True)
        batch_op.drop_column('contra')
        batch_op.drop_column('favor')

    # ### end Alembic commands ###
