"""uemc order

Revision ID: 46ae9be4fd4d
Revises: 483cb79e253f
Create Date: 2025-04-14 19:06:05.809045

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '46ae9be4fd4d'
down_revision = '483cb79e253f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('uemc_partidos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('orden', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('uemc_partidos', schema=None) as batch_op:
        batch_op.drop_column('orden')

    # ### end Alembic commands ###
