"""uemc

Revision ID: 483cb79e253f
Revises: c18afc233368
Create Date: 2025-04-14 18:44:19.634333

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '483cb79e253f'
down_revision = 'c18afc233368'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('uemc_partidos', schema=None) as batch_op:
        batch_op.alter_column('fecha',
               existing_type=sa.DATE(),
               type_=sa.String(length=20),
               nullable=True)
        batch_op.alter_column('hora',
               existing_type=postgresql.TIME(),
               type_=sa.String(length=20),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('uemc_partidos', schema=None) as batch_op:
        batch_op.alter_column('hora',
               existing_type=sa.String(length=20),
               type_=postgresql.TIME(),
               nullable=False)
        batch_op.alter_column('fecha',
               existing_type=sa.String(length=20),
               type_=sa.DATE(),
               nullable=False)

    # ### end Alembic commands ###
