"""jornada_perm

Revision ID: 4989f3f80865
Revises: 94b7054752e8
Create Date: 2026-05-12 16:36:26.753532

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4989f3f80865'
down_revision = '94b7054752e8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('jornada_permanencia_aula',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('jornada_permanencia_aula')
    # ### end Alembic commands ###
