"""fecha1

Revision ID: 4e69153887e5
Revises: 95959f40a772
Create Date: 2026-06-21 17:37:10.393450

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4e69153887e5'
down_revision = '95959f40a772'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('aliados_partidos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fecha1', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('aliados_partidos', schema=None) as batch_op:
        batch_op.drop_column('fecha1')

    # ### end Alembic commands ###
