"""aliados_cup

Revision ID: 5a6a024dd2b1
Revises: 4592a9542110
Create Date: 2026-05-15 20:05:17.037986

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5a6a024dd2b1'
down_revision = '4592a9542110'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('jornada_eurocup',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('clasificacion_eurocup')
    with op.batch_alter_table('eurocup_aliados', schema=None) as batch_op:
        batch_op.add_column(sa.Column('jornada_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'jornada_eurocup', ['jornada_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('eurocup_aliados', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('jornada_id')

    op.create_table('clasificacion_eurocup',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('grupo', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('equipo', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('jugados', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('ganados', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('perdidos', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('puntos', sa.VARCHAR(length=150), autoincrement=False, nullable=True),
    sa.Column('favor', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('contra', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='clasificacion_eurocup_pkey')
    )
    op.drop_table('jornada_eurocup')
    # ### end Alembic commands ###
