"""string_aula

Revision ID: 63d43129d849
Revises: 6bcd970c391a
Create Date: 2026-05-12 19:38:13.134781

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '63d43129d849'
down_revision = '6bcd970c391a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('aula_partidos', schema=None) as batch_op:
        batch_op.alter_column('resultadoA',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=120),
               existing_nullable=True)
        batch_op.alter_column('resultadoB',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=120),
               existing_nullable=True)

    with op.batch_alter_table('copa_aula', schema=None) as batch_op:
        batch_op.alter_column('resultadoA',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=120),
               existing_nullable=True)
        batch_op.alter_column('resultadoB',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=120),
               existing_nullable=True)

    with op.batch_alter_table('europa_aula', schema=None) as batch_op:
        batch_op.alter_column('resultadoA',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=120),
               existing_nullable=True)
        batch_op.alter_column('resultadoB',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=120),
               existing_nullable=True)

    with op.batch_alter_table('permanencia_aula', schema=None) as batch_op:
        batch_op.alter_column('resultadoA',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=120),
               existing_nullable=True)
        batch_op.alter_column('resultadoB',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=120),
               existing_nullable=True)

    with op.batch_alter_table('playoff_aula', schema=None) as batch_op:
        batch_op.alter_column('resultadoA',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=120),
               existing_nullable=True)
        batch_op.alter_column('resultadoB',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=120),
               existing_nullable=True)

    with op.batch_alter_table('supercopa_iberica_aula', schema=None) as batch_op:
        batch_op.alter_column('resultadoA',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=120),
               existing_nullable=True)
        batch_op.alter_column('resultadoB',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=120),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('supercopa_iberica_aula', schema=None) as batch_op:
        batch_op.alter_column('resultadoB',
               existing_type=sa.String(length=120),
               type_=sa.INTEGER(),
               existing_nullable=True)
        batch_op.alter_column('resultadoA',
               existing_type=sa.String(length=120),
               type_=sa.INTEGER(),
               existing_nullable=True)

    with op.batch_alter_table('playoff_aula', schema=None) as batch_op:
        batch_op.alter_column('resultadoB',
               existing_type=sa.String(length=120),
               type_=sa.INTEGER(),
               existing_nullable=True)
        batch_op.alter_column('resultadoA',
               existing_type=sa.String(length=120),
               type_=sa.INTEGER(),
               existing_nullable=True)

    with op.batch_alter_table('permanencia_aula', schema=None) as batch_op:
        batch_op.alter_column('resultadoB',
               existing_type=sa.String(length=120),
               type_=sa.INTEGER(),
               existing_nullable=True)
        batch_op.alter_column('resultadoA',
               existing_type=sa.String(length=120),
               type_=sa.INTEGER(),
               existing_nullable=True)

    with op.batch_alter_table('europa_aula', schema=None) as batch_op:
        batch_op.alter_column('resultadoB',
               existing_type=sa.String(length=120),
               type_=sa.INTEGER(),
               existing_nullable=True)
        batch_op.alter_column('resultadoA',
               existing_type=sa.String(length=120),
               type_=sa.INTEGER(),
               existing_nullable=True)

    with op.batch_alter_table('copa_aula', schema=None) as batch_op:
        batch_op.alter_column('resultadoB',
               existing_type=sa.String(length=120),
               type_=sa.INTEGER(),
               existing_nullable=True)
        batch_op.alter_column('resultadoA',
               existing_type=sa.String(length=120),
               type_=sa.INTEGER(),
               existing_nullable=True)

    with op.batch_alter_table('aula_partidos', schema=None) as batch_op:
        batch_op.alter_column('resultadoB',
               existing_type=sa.String(length=120),
               type_=sa.INTEGER(),
               existing_nullable=True)
        batch_op.alter_column('resultadoA',
               existing_type=sa.String(length=120),
               type_=sa.INTEGER(),
               existing_nullable=True)

    # ### end Alembic commands ###
