"""salva

Revision ID: 650e760e2e16
Revises: dceb3a1dd69e
Create Date: 2026-07-13 16:57:23.295460

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '650e760e2e16'
down_revision = 'dceb3a1dd69e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('jornadas_salvador', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fase', sa.String(length=30), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('jornadas_salvador', schema=None) as batch_op:
        batch_op.drop_column('fase')

    # ### end Alembic commands ###
