"""copa rey recoletas

Revision ID: 688d8ed0f282
Revises: cf7899658435
Create Date: 2026-02-03 16:42:42.819229

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '688d8ed0f282'
down_revision = 'cf7899658435'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('copa_rey_recoletas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('eliminatoria', sa.String(length=20), nullable=False),
    sa.Column('fecha', sa.String(length=20), nullable=True),
    sa.Column('hora', sa.String(length=10), nullable=True),
    sa.Column('local', sa.String(length=100), nullable=True),
    sa.Column('resultadoA', sa.String(length=10), nullable=True),
    sa.Column('resultadoB', sa.String(length=10), nullable=True),
    sa.Column('visitante', sa.String(length=100), nullable=True),
    sa.Column('orden', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('copa_rey_recoletas')
    # ### end Alembic commands ###
