"""encuentros

Revision ID: 6ee9338863f2
Revises: 34acafb3aa71
Create Date: 2026-01-23 13:40:45.021777

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6ee9338863f2'
down_revision = '34acafb3aa71'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('playoff_ponce', schema=None) as batch_op:
        batch_op.add_column(sa.Column('encuentros', sa.String(length=20), nullable=False))
        batch_op.drop_column('eliminatoria')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('playoff_ponce', schema=None) as batch_op:
        batch_op.add_column(sa.Column('eliminatoria', sa.VARCHAR(length=20), autoincrement=False, nullable=False))
        batch_op.drop_column('encuentros')

    # ### end Alembic commands ###
