"""fases

Revision ID: 716deaa7e4f6
Revises: 5a6a024dd2b1
Create Date: 2026-05-22 14:59:51.386813

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '716deaa7e4f6'
down_revision = '5a6a024dd2b1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('jornadas_vrac', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fase', sa.String(length=20), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('jornadas_vrac', schema=None) as batch_op:
        batch_op.drop_column('fase')

    # ### end Alembic commands ###
