"""temp

Revision ID: 740bbe4d70d5
Revises: df30d2ab694a
Create Date: 2026-06-30 19:49:00.745148

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '740bbe4d70d5'
down_revision = 'df30d2ab694a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('temporadas_parquesol',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=20), nullable=False),
    sa.Column('activa', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre')
    )
    op.create_table('temporadas_recoletas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=20), nullable=False),
    sa.Column('activa', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre')
    )
    with op.batch_alter_table('jornadas_parquesol', schema=None) as batch_op:
        batch_op.add_column(sa.Column('temporada_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'temporadas_parquesol', ['temporada_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('jornadas_recoletas', schema=None) as batch_op:
        batch_op.add_column(sa.Column('temporada_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'temporadas_recoletas', ['temporada_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('jornadas_recoletas', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('temporada_id')

    with op.batch_alter_table('jornadas_parquesol', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('temporada_id')

    op.drop_table('temporadas_recoletas')
    op.drop_table('temporadas_parquesol')
    # ### end Alembic commands ###
