"""crear configuracion de menu de competiciones

Revision ID: 78056c823e56
Revises: 234864163aaa
Create Date: 2026-08-16 12:42:14.762997

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '78056c823e56'
down_revision = '234864163aaa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('secciones_config',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('activa', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre')
    )
    op.create_table('competiciones_config',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('seccion_id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('activa', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['seccion_id'], ['secciones_config.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('seccion_id', 'nombre', name='uq_seccion_competicion')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('competiciones_config')
    op.drop_table('secciones_config')
    # ### end Alembic commands ###
