"""valladoliDi

Revision ID: 7a02fd9f89cb
Revises: 78056c823e56
Create Date: 2026-08-19 17:39:49.633598

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7a02fd9f89cb'
down_revision = '78056c823e56'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('temporadas_vallad_genius',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=20), nullable=False),
    sa.Column('activa', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre')
    )
    op.create_table('vallad_genius_clubs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('vallad_genius_grupos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=20), nullable=False),
    sa.Column('fase', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('jornadas_vallad_genius',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('temporada_id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['temporada_id'], ['temporadas_vallad_genius.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('vallad_genius_grupos_equipos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('grupo_id', sa.Integer(), nullable=False),
    sa.Column('equipo', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['grupo_id'], ['vallad_genius_grupos.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('vallad_genius_partidos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('jornada_id', sa.Integer(), nullable=False),
    sa.Column('fecha', sa.String(length=25), nullable=True),
    sa.Column('hora', sa.String(length=25), nullable=True),
    sa.Column('local', sa.String(length=255), nullable=True),
    sa.Column('resultadoA', sa.String(length=120), nullable=True),
    sa.Column('resultadoB', sa.String(length=120), nullable=True),
    sa.Column('visitante', sa.String(length=255), nullable=True),
    sa.Column('orden', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['jornada_id'], ['jornadas_vallad_genius.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('vallad_genius_partidos')
    op.drop_table('vallad_genius_grupos_equipos')
    op.drop_table('jornadas_vallad_genius')
    op.drop_table('vallad_genius_grupos')
    op.drop_table('vallad_genius_clubs')
    op.drop_table('temporadas_vallad_genius')
    # ### end Alembic commands ###
