"""temporadas

Revision ID: 7df8dd1633f8
Revises: 7e68b7cc827f
Create Date: 2026-06-29 15:09:52.561823

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7df8dd1633f8'
down_revision = '7e68b7cc827f'
branch_labels = None
depends_on = None


def upgrade():
    op.add_column(
        'jornadas_valladolid',
        sa.Column('temporada_id', sa.Integer(), nullable=True)
    )

    op.create_foreign_key(
        'fk_jornadas_temporada',
        'jornadas_valladolid',
        'temporadas',
        ['temporada_id'],
        ['id']
    )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('jornadas_valladolid') as batch_op:
        batch_op.add_column(sa.Column('temporada_id', sa.Integer(), nullable=False)
        )

    op.drop_table('temporadas')
    # ### end Alembic commands ###
