"""puce

Revision ID: 7e34b9a2dfdf
Revises: 650e760e2e16
Create Date: 2026-07-13 18:50:37.822635

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7e34b9a2dfdf'
down_revision = '650e760e2e16'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('historial',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('deporte', sa.String(length=30), nullable=False),
    sa.Column('equipo', sa.String(length=80), nullable=False),
    sa.Column('temporada', sa.String(length=20), nullable=False),
    sa.Column('liga', sa.String(length=80), nullable=True),
    sa.Column('puntos', sa.Integer(), nullable=True),
    sa.Column('puesto', sa.Integer(), nullable=True),
    sa.Column('playoff', sa.String(length=80), nullable=True),
    sa.Column('copa', sa.String(length=80), nullable=True),
    sa.Column('titulos', sa.String(length=150), nullable=True),
    sa.Column('siguiente_temporada', sa.String(length=80), nullable=True),
    sa.Column('observaciones', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('palmaress',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('deporte', sa.String(length=30), nullable=False),
    sa.Column('equipo', sa.String(length=80), nullable=False),
    sa.Column('temporada', sa.String(length=20), nullable=False),
    sa.Column('competicion', sa.String(length=100), nullable=True),
    sa.Column('imagen', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('historial_valladolid')
    op.drop_table('palmares')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('palmares',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('temporada_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('competicion', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('imagen', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['temporada_id'], ['temporadas_valladolid.id'], name='palmares_temporada_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='palmares_pkey')
    )
    op.create_table('historial_valladolid',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('temporada_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('liga', sa.VARCHAR(length=80), autoincrement=False, nullable=False),
    sa.Column('puntos', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('puesto', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('playoff', sa.VARCHAR(length=80), autoincrement=False, nullable=True),
    sa.Column('copa', sa.VARCHAR(length=80), autoincrement=False, nullable=True),
    sa.Column('titulos', sa.VARCHAR(length=150), autoincrement=False, nullable=True),
    sa.Column('observaciones', sa.VARCHAR(length=200), autoincrement=False, nullable=True),
    sa.Column('siguiente_temporada', sa.VARCHAR(length=80), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['temporada_id'], ['temporadas_valladolid.id'], name='historial_valladolid_temporada_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='historial_valladolid_pkey')
    )
    op.drop_table('palmaress')
    op.drop_table('historial')
    # ### end Alembic commands ###
