"""fecha1

Revision ID: 7e68b7cc827f
Revises: 4e69153887e5
Create Date: 2026-06-21 17:54:01.391889

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7e68b7cc827f'
down_revision = '4e69153887e5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('aliados_partidos', schema=None) as batch_op:
        batch_op.drop_column('fecha1')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('aliados_partidos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fecha1', sa.VARCHAR(length=20), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
