"""histo_vallad

Revision ID: 877eadde4c64
Revises: 2a43a12df4ae
Create Date: 2026-07-09 15:49:40.394329

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '877eadde4c64'
down_revision = '2a43a12df4ae'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('historial_valladolid',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('temporada_id', sa.Integer(), nullable=False),
    sa.Column('liga', sa.String(length=80), nullable=False),
    sa.Column('puntos', sa.Integer(), nullable=True),
    sa.Column('puesto', sa.Integer(), nullable=True),
    sa.Column('playoff', sa.String(length=80), nullable=True),
    sa.Column('copa', sa.String(length=80), nullable=True),
    sa.Column('titulos', sa.String(length=150), nullable=True),
    sa.Column('observaciones', sa.String(length=200), nullable=True),
    sa.ForeignKeyConstraint(['temporada_id'], ['temporadas_valladolid.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('historial_valladolid')
    # ### end Alembic commands ###
