"""permanencia_aula

Revision ID: 8f03f7d11b5c
Revises: 4989f3f80865
Create Date: 2026-05-12 16:40:26.895788

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8f03f7d11b5c'
down_revision = '4989f3f80865'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('permanencia_aula', schema=None) as batch_op:
        batch_op.add_column(sa.Column('jornada_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'jornada_permanencia_aula', ['jornada_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('permanencia_aula', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('jornada_id')

    # ### end Alembic commands ###
