"""europa

Revision ID: 921adc37b5d0
Revises: 2aaff7ccbbcc
Create Date: 2026-07-14 16:48:37.616501

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '921adc37b5d0'
down_revision = '2aaff7ccbbcc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('historial', schema=None) as batch_op:
        batch_op.add_column(sa.Column('europa', sa.String(length=80), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('historial', schema=None) as batch_op:
        batch_op.drop_column('europa')

    # ### end Alembic commands ###
