"""temp_vall

Revision ID: 92ed9aa9f905
Revises: 353478d6159d
Create Date: 2026-06-29 20:07:37.743988

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '92ed9aa9f905'
down_revision = '353478d6159d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('temporadas_valladolid',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=20), nullable=False),
    sa.Column('activa', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre')
    )
    with op.batch_alter_table('jornadas_valladolid', schema=None) as batch_op:
        batch_op.alter_column('temporada_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.create_foreign_key(None, 'temporadas_valladolid', ['temporada_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('jornadas_valladolid', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('temporada_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    op.drop_table('temporadas_valladolid')
    # ### end Alembic commands ###
