"""permanencia_aula

Revision ID: 94b7054752e8
Revises: e98f3d637e4e
Create Date: 2026-05-12 15:48:24.259062

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '94b7054752e8'
down_revision = 'e98f3d637e4e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('permanencia_aula',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fase', sa.String(length=20), nullable=False),
    sa.Column('fecha', sa.String(length=20), nullable=True),
    sa.Column('hora', sa.String(length=10), nullable=True),
    sa.Column('local', sa.String(length=100), nullable=True),
    sa.Column('resultadoA', sa.Integer(), nullable=True),
    sa.Column('resultadoB', sa.Integer(), nullable=True),
    sa.Column('visitante', sa.String(length=100), nullable=True),
    sa.Column('orden', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('aula_partidos', schema=None) as batch_op:
        batch_op.alter_column('resultadoA',
              existing_type=sa.VARCHAR(length=10),
              type_=sa.Integer(),
              existing_nullable=True,
              postgresql_using='"resultadoA"::integer'
       )
        batch_op.alter_column('resultadoB',
              existing_type=sa.VARCHAR(length=10),
              type_=sa.Integer(),
              existing_nullable=True,
              postgresql_using='"resultadoB"::integer'
        )

    with op.batch_alter_table('copa_aula', schema=None) as batch_op:
        batch_op.alter_column('resultadoA',
              existing_type=sa.VARCHAR(length=10),
              type_=sa.Integer(),
              existing_nullable=True,
              postgresql_using='"resultadoA"::integer'
        )
        batch_op.alter_column('resultadoB',
              existing_type=sa.VARCHAR(length=10),
              type_=sa.Integer(),
              existing_nullable=True,
              postgresql_using='"resultadoB"::integer'
        )

    with op.batch_alter_table('copa_uemc', schema=None) as batch_op:
        batch_op.alter_column('resultadoA',
               existing_type=sa.VARCHAR(length=120),
               type_=sa.Integer(),
               existing_nullable=True,
               postgresql_using='"resultadoA"::integer'
        )
        batch_op.alter_column('resultadoB',
               existing_type=sa.VARCHAR(length=120),
               type_=sa.Integer(),
               existing_nullable=True,
               postgresql_using='"resultadoB"::integer'
        )

    with op.batch_alter_table('europa_aula', schema=None) as batch_op:
        batch_op.alter_column('resultadoA',
               existing_type=sa.VARCHAR(length=10),
               type_=sa.Integer(),
               existing_nullable=True,
               postgresql_using='"resultadoA"::integer'
        )
        batch_op.alter_column('resultadoB',
               existing_type=sa.VARCHAR(length=10),
               type_=sa.Integer(),
               existing_nullable=True,
               postgresql_using='"resultadoB"::integer'
        )

    with op.batch_alter_table('playoff_aula', schema=None) as batch_op:
        batch_op.alter_column('resultadoA',
               existing_type=sa.VARCHAR(length=10),
               type_=sa.Integer(),
               existing_nullable=True,
               postgresql_using='"resultadoA"::integer'
        )
        batch_op.alter_column('resultadoB',
               existing_type=sa.VARCHAR(length=10),
               type_=sa.Integer(),
               existing_nullable=True,
               postgresql_using='"resultadoB"::integer'
        )

    with op.batch_alter_table('supercopa_iberica_aula', schema=None) as batch_op:
        batch_op.alter_column('resultadoA',
               existing_type=sa.VARCHAR(length=10),
               type_=sa.Integer(),
               existing_nullable=True,
               postgresql_using='"resultadoA"::integer'
        )
        batch_op.alter_column('resultadoB',
               existing_type=sa.VARCHAR(length=10),
               type_=sa.Integer(),
               existing_nullable=True,
               postgresql_using='"resultadoB"::integer'
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('supercopa_iberica_aula', schema=None) as batch_op:
        batch_op.alter_column('resultadoB',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(length=10),
               existing_nullable=True,
               postgresql_using='"resultadoB"::integer'
        )
        batch_op.alter_column('resultadoA',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(length=10),
               existing_nullable=True,
               postgresql_using='"resultadoA"::integer'
        )

    with op.batch_alter_table('playoff_aula', schema=None) as batch_op:
        batch_op.alter_column('resultadoB',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(length=10),
               existing_nullable=True,
               postgresql_using='"resultadoB"::integer'
        )
        batch_op.alter_column('resultadoA',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(length=10),
               existing_nullable=True,
               postgresql_using='"resultadoA"::integer'
        )

    with op.batch_alter_table('europa_aula', schema=None) as batch_op:
        batch_op.alter_column('resultadoB',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(length=10),
               existing_nullable=True,
               postgresql_using='"resultadoB"::integer'
        )
        batch_op.alter_column('resultadoA',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(length=10),
               existing_nullable=True,
               postgresql_using='"resultadoA"::integer'
        )

    with op.batch_alter_table('copa_uemc', schema=None) as batch_op:
        batch_op.alter_column('resultadoB',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(length=120),
               existing_nullable=True,
               postgresql_using='"resultadoB"::integer'
        )
        batch_op.alter_column('resultadoA',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(length=120),
               existing_nullable=True,
               postgresql_using='"resultadoA"::integer'
        )

    with op.batch_alter_table('copa_aula', schema=None) as batch_op:
        batch_op.alter_column('resultadoB',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(length=10),
               existing_nullable=True,
               postgresql_using='"resultadoB"::integer'
        )
        batch_op.alter_column('resultadoA',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(length=10),
               existing_nullable=True,
               postgresql_using='"resultadoA"::integer'
        )

    with op.batch_alter_table('aula_partidos', schema=None) as batch_op:
        batch_op.alter_column('resultadoB',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(length=120),
               existing_nullable=True,
               postgresql_using='"resultadoB"::integer'
        )
        batch_op.alter_column('resultadoA',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(length=120),
               existing_nullable=True,
               postgresql_using='"resultadoA"::integer'
        )

    op.drop_table('permanencia_aula')
    # ### end Alembic commands ###
