"""recoletas

Revision ID: 95911cfb2924
Revises: 688d8ed0f282
Create Date: 2026-02-03 17:54:12.617295

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '95911cfb2924'
down_revision = '688d8ed0f282'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('copa_españa_recoletas')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('copa_españa_recoletas',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('eliminatoria', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('fecha', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('hora', sa.VARCHAR(length=10), autoincrement=False, nullable=True),
    sa.Column('local', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('resultadoA', sa.VARCHAR(length=10), autoincrement=False, nullable=True),
    sa.Column('resultadoB', sa.VARCHAR(length=10), autoincrement=False, nullable=True),
    sa.Column('visitante', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('orden', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='copa_españa_recoletas_pkey')
    )
    # ### end Alembic commands ###
