"""sanjose

Revision ID: 95959f40a772
Revises: b6d4c2669819
Create Date: 2026-06-15 21:43:47.770474

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '95959f40a772'
down_revision = 'b6d4c2669819'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('san_jose_partidos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('puntosA', sa.String(length=225), nullable=True))
        batch_op.add_column(sa.Column('puntosB', sa.String(length=225), nullable=True))
        batch_op.drop_column('bonusA')
        batch_op.drop_column('bonusB')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('san_jose_partidos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('bonusB', sa.VARCHAR(length=120), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('bonusA', sa.VARCHAR(length=120), autoincrement=False, nullable=True))
        batch_op.drop_column('puntosB')
        batch_op.drop_column('puntosA')

    # ### end Alembic commands ###
