"""parquesol

Revision ID: a53d71daf4a6
Revises: 4fe30061e95a
Create Date: 2026-07-12 11:26:12.880611

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a53d71daf4a6'
down_revision = '4fe30061e95a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('historial_parquesol',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('temporada_id', sa.Integer(), nullable=False),
    sa.Column('liga', sa.String(length=80), nullable=False),
    sa.Column('puntos', sa.Integer(), nullable=True),
    sa.Column('puesto', sa.Integer(), nullable=True),
    sa.Column('playoff', sa.String(length=80), nullable=True),
    sa.Column('copa', sa.String(length=80), nullable=True),
    sa.Column('titulos', sa.String(length=150), nullable=True),
    sa.Column('siguiente_temporada', sa.String(length=80), nullable=True),
    sa.Column('observaciones', sa.String(length=200), nullable=True),
    sa.ForeignKeyConstraint(['temporada_id'], ['temporadas_parquesol.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('palmares_parquesol',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('temporada_id', sa.Integer(), nullable=False),
    sa.Column('competicion', sa.String(length=100), nullable=False),
    sa.Column('imagen', sa.String(length=100), nullable=False),
    sa.ForeignKeyConstraint(['temporada_id'], ['temporadas_parquesol.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('palmares_parquesol')
    op.drop_table('historial_parquesol')
    # ### end Alembic commands ###
