"""his_vall

Revision ID: a8074c20ea37
Revises: 877eadde4c64
Create Date: 2026-07-09 19:20:12.449334

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a8074c20ea37'
down_revision = '877eadde4c64'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('historial_valladolid', schema=None) as batch_op:
        batch_op.add_column(sa.Column('siguiente_competicion', sa.String(length=80), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('historial_valladolid', schema=None) as batch_op:
        batch_op.drop_column('siguiente_competicion')

    # ### end Alembic commands ###
