"""order

Revision ID: ad055aa411ce
Revises: d0f68333d86a
Create Date: 2025-04-10 21:18:39.027564

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ad055aa411ce'
down_revision = 'd0f68333d86a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('valladolid_partidos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('orden', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('valladolid_partidos', schema=None) as batch_op:
        batch_op.drop_column('orden')

    # ### end Alembic commands ###
