"""sig_temp

Revision ID: af289253f9d4
Revises: a8074c20ea37
Create Date: 2026-07-09 19:25:29.155368

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'af289253f9d4'
down_revision = 'a8074c20ea37'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('historial_valladolid', schema=None) as batch_op:
        batch_op.add_column(sa.Column('siguiente_temporada', sa.String(length=80), nullable=True))
        batch_op.drop_column('siguiente_competicion')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('historial_valladolid', schema=None) as batch_op:
        batch_op.add_column(sa.Column('siguiente_competicion', sa.VARCHAR(length=80), autoincrement=False, nullable=True))
        batch_op.drop_column('siguiente_temporada')

    # ### end Alembic commands ###
