"""palmares

Revision ID: b5091ba40f9f
Revises: af289253f9d4
Create Date: 2026-07-10 17:36:16.951675

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b5091ba40f9f'
down_revision = 'af289253f9d4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('palmares',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('temporada_id', sa.Integer(), nullable=False),
    sa.Column('competicion', sa.String(length=100), nullable=False),
    sa.Column('imagen', sa.String(length=100), nullable=False),
    sa.ForeignKeyConstraint(['temporada_id'], ['temporadas_valladolid.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('palmares')
    # ### end Alembic commands ###
