"""uemc

Revision ID: b661e077aed4
Revises: 740bbe4d70d5
Create Date: 2026-07-01 15:42:31.954589

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b661e077aed4'
down_revision = '740bbe4d70d5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('temporadas_uemc',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=20), nullable=False),
    sa.Column('activa', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre')
    )
    with op.batch_alter_table('jornadas_uemc', schema=None) as batch_op:
        batch_op.add_column(sa.Column('temporada_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'temporadas_uemc', ['temporada_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('jornadas_uemc', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('temporada_id')

    op.drop_table('temporadas_uemc')
    # ### end Alembic commands ###
