"""vcv

Revision ID: b6d4c2669819
Revises: c4a7b2e2047e
Create Date: 2026-06-15 16:20:45.926512

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b6d4c2669819'
down_revision = 'c4a7b2e2047e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vcv_partidos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('puntosA', sa.String(length=225), nullable=True))
        batch_op.add_column(sa.Column('puntosB', sa.String(length=225), nullable=True))
        batch_op.drop_column('bonusA')
        batch_op.drop_column('bonusB')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vcv_partidos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('bonusB', sa.VARCHAR(length=120), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('bonusA', sa.VARCHAR(length=120), autoincrement=False, nullable=True))
        batch_op.drop_column('puntosB')
        batch_op.drop_column('puntosA')

    # ### end Alembic commands ###
