"""date

Revision ID: b7246fc92931
Revises: 640858df2d13
Create Date: 2025-04-29 12:52:38.947587

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'b7246fc92931'
down_revision = '640858df2d13'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('copa_uemc', schema=None) as batch_op:
        batch_op.alter_column('fecha',
               existing_type=sa.DATE(),
               type_=sa.String(length=20),
               nullable=True)
        batch_op.alter_column('hora',
               existing_type=postgresql.TIME(),
               type_=sa.String(length=20),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('copa_uemc', schema=None) as batch_op:
        batch_op.alter_column('hora',
               existing_type=sa.String(length=20),
               type_=postgresql.TIME(),
               nullable=False)
        batch_op.alter_column('fecha',
               existing_type=sa.String(length=20),
               type_=sa.DATE(),
               nullable=False)

    # ### end Alembic commands ###
