"""bonus

Revision ID: b7b98841634e
Revises: 16477e4a6c04
Create Date: 2025-05-18 16:25:26.453529

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b7b98841634e'
down_revision = '16477e4a6c04'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('clasificacion_euro_caja', schema=None) as batch_op:
        batch_op.add_column(sa.Column('bonus', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('clasificacion_euro_caja', schema=None) as batch_op:
        batch_op.drop_column('bonus')

    # ### end Alembic commands ###
