"""Nuevas tabals

Revision ID: ba11f38243c4
Revises: 43bd3d304a36
Create Date: 2026-01-22 18:24:36.068371

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ba11f38243c4'
down_revision = '43bd3d304a36'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clasificacion_eurocup',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('grupo', sa.String(length=50), nullable=True),
    sa.Column('equipo', sa.String(length=50), nullable=True),
    sa.Column('jugados', sa.Integer(), nullable=True),
    sa.Column('ganados', sa.Integer(), nullable=True),
    sa.Column('perdidos', sa.Integer(), nullable=True),
    sa.Column('puntos', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('eurocup_aliados',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('encuentros', sa.String(length=255), nullable=True),
    sa.Column('fecha', sa.String(length=20), nullable=True),
    sa.Column('hora', sa.String(length=20), nullable=True),
    sa.Column('local', sa.String(length=255), nullable=True),
    sa.Column('resultadoA', sa.String(length=120), nullable=True),
    sa.Column('resultadoB', sa.String(length=120), nullable=True),
    sa.Column('visitante', sa.String(length=255), nullable=True),
    sa.Column('orden', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('eurocup_aliados')
    op.drop_table('clasificacion_eurocup')
    # ### end Alembic commands ###
