"""encuentros

Revision ID: c0aec13066d3
Revises: e08165c6ddb8
Create Date: 2025-05-02 16:08:18.846217

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c0aec13066d3'
down_revision = 'e08165c6ddb8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('europa_recoletas', schema=None) as batch_op:
        batch_op.add_column(sa.Column('encuentros', sa.String(length=20), nullable=False))
        batch_op.drop_column('eliminatoria')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('europa_recoletas', schema=None) as batch_op:
        batch_op.add_column(sa.Column('eliminatoria', sa.VARCHAR(length=20), autoincrement=False, nullable=False))
        batch_op.drop_column('encuentros')

    # ### end Alembic commands ###
