"""hora

Revision ID: c18afc233368
Revises: f68e743f94f8
Create Date: 2025-04-11 22:01:26.724918

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'c18afc233368'
down_revision = 'f68e743f94f8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('simancas_partidos', schema=None) as batch_op:
        batch_op.alter_column('hora',
               existing_type=postgresql.TIME(),
               type_=sa.String(length=25),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('simancas_partidos', schema=None) as batch_op:
        batch_op.alter_column('hora',
               existing_type=sa.String(length=25),
               type_=postgresql.TIME(),
               nullable=False)

    # ### end Alembic commands ###
