"""cbc

Revision ID: da971c351b6e
Revises: 282b9818d3ff
Create Date: 2026-07-22 16:48:42.411689

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'da971c351b6e'
down_revision = '282b9818d3ff'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('equipos_copa_uemc',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('grupo', sa.String(length=1), nullable=True),
    sa.Column('equipo', sa.String(length=120), nullable=True),
    sa.Column('orden', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('equipo')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('equipos_copa_uemc')
    # ### end Alembic commands ###
