"""vrac2

Revision ID: dceb3a1dd69e
Revises: 3a18173af5f2
Create Date: 2026-07-13 12:55:26.200152

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dceb3a1dd69e'
down_revision = '3a18173af5f2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('jornadas_vrac', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fase', sa.String(length=30), nullable=True))

    with op.batch_alter_table('vrac_partidos', schema=None) as batch_op:
        batch_op.drop_column('fase')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vrac_partidos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fase', sa.VARCHAR(length=30), autoincrement=False, nullable=True))

    with op.batch_alter_table('jornadas_vrac', schema=None) as batch_op:
        batch_op.drop_column('fase')

    # ### end Alembic commands ###
