"""palmares

Revision ID: dd132aceebd8
Revises: da971c351b6e
Create Date: 2026-07-22 18:58:26.729513

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dd132aceebd8'
down_revision = 'da971c351b6e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('palmaress', schema=None) as batch_op:
        batch_op.add_column(sa.Column('orden', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('palmaress', schema=None) as batch_op:
        batch_op.drop_column('orden')

    # ### end Alembic commands ###
