"""tabla playoff_uemc

Revision ID: e06e7f51c5b8
Revises: 302d3a4d0881
Create Date: 2025-04-09 12:47:36.652584

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e06e7f51c5b8'
down_revision = '302d3a4d0881'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('playoff_uemc',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('eliminatoria', sa.String(length=20), nullable=False),
    sa.Column('fecha', sa.String(length=20), nullable=True),
    sa.Column('hora', sa.String(length=10), nullable=True),
    sa.Column('local', sa.String(length=100), nullable=True),
    sa.Column('resultadoA', sa.String(length=10), nullable=True),
    sa.Column('resultadoB', sa.String(length=10), nullable=True),
    sa.Column('visitante', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('playoff_uemc')
    # ### end Alembic commands ###
