"""order

Revision ID: e343d9d2733d
Revises: e06e7f51c5b8
Create Date: 2025-04-09 20:52:54.110386

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e343d9d2733d'
down_revision = 'e06e7f51c5b8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('playoff_uemc', schema=None) as batch_op:
        batch_op.add_column(sa.Column('orden', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('playoff_uemc', schema=None) as batch_op:
        batch_op.drop_column('orden')

    # ### end Alembic commands ###
