COMERCIAL = {
    "uemc": {
        "amazon": {
            "seccion": [],
            "calendario": [],
            "resultados": [],
            "clasificacion": [],
            "historial": [],
            "temporadas": [],
            "puntos": [],
            "palmares": [],
            "sistema_ligas": [],
        },
        "publicidad": {
            "seccion": False,
            "calendario": False,
            "resultados": False,
            "clasificacion": False,
            "historial": False,
            "temporadas": False,
            "puntos": False,
            "palmares": False,
            "sistema_ligas": False,
        },
        "patrocinador": {
            "seccion": None,
            "calendario": None,
            "resultados": None,
            "clasificacion": None,
            "historial": None,
            "temporadas": None,
            "puntos": None,
            "palmares": None,
            "sistema_ligas": None,
        },
    },
    "ponce": {
            "amazon": {
                "seccion": [
                ],
                "calendario": [],
                "resultados": [],
                "clasificacion": [],
                "historial": [],
                "temporadas": [],
                "puntos": [],
                "palmares": [],
                "sistema_ligas": [],
            },
            "publicidad": {
                "seccion": False,
                "calendario": False,
                "resultados": False,
                "clasificacion": False,
                "historial": False,
                "temporadas": False,
                "puntos": False,
                "palmares": False,
                "sistema_ligas": False,
            },
            "patrocinador": {
                "seccion": None,
                "calendario": None,
                "resultados": None,
                "clasificacion": None,
                "historial": None,
                "temporadas": None,
                "puntos": None,
                "palmares": None,
                "sistema_ligas": None,
            },
        },
    "cdsi": {
            "amazon": {
                "seccion": [
                ],
                "calendario": [],
                "resultados": [],
                "clasificacion": [],
                "historial": [],
                "temporadas": [],
                "puntos": [],
                "palmares": [],
                "sistema_ligas": [],
            },
            "publicidad": {
                "seccion": False,
                "calendario": False,
                "resultados": False,
                "clasificacion": False,
                "historial": False,
                "temporadas": False,
                "puntos": False,
                "palmares": False,
                "sistema_ligas": False,
            },
            "patrocinador": {
                "seccion": None,
                "calendario": None,
                "resultados": None,
                "clasificacion": None,
                "historial": None,
                "temporadas": None,
                "puntos": None,
                "palmares": None,
                "sistema_ligas": None,
            },
        },
    "aliados": {
            "amazon": {
                "seccion": [
                ],
                "calendario": [],
                "resultados": [],
                "clasificacion": [],
                "historial": [],
                "temporadas": [],
                "puntos": [],
                "palmares": [],
                "sistema_ligas": [],
            },
            "publicidad": {
                "seccion": False,
                "calendario": False,
                "resultados": False,
                "clasificacion": False,
                "historial": False,
                "temporadas": False,
                "puntos": False,
                "palmares": False,
                "sistema_ligas": False,
            },
            "patrocinador": {
                "seccion": None,
                "calendario": None,
                "resultados": None,
                "clasificacion": None,
                "historial": None,
                "temporadas": None,
                "puntos": None,
                "palmares": None,
                "sistema_ligas": None,
            },
        },
    "aula": {
            "amazon": {
                "seccion": [
                ],
                "calendario": [],
                "resultados": [],
                "clasificacion": [],
                "historial": [],
                "temporadas": [],
                "puntos": [],
                "palmares": [],
                "sistema_ligas": [],
            },
            "publicidad": {
                "seccion": False,
                "calendario": False,
                "resultados": False,
                "clasificacion": False,
                "historial": False,
                "temporadas": False,
                "puntos": False,
                "palmares": False,
                "sistema_ligas": False,
            },
            "patrocinador": {
                "seccion": None,
                "calendario": None,
                "resultados": None,
                "clasificacion": None,
                "historial": None,
                "temporadas": None,
                "puntos": None,
                "palmares": None,
                "sistema_ligas": None,
            },
        },
    "recoletas": {
            "amazon": {
                "seccion": [
                ],
                "calendario": [],
                "resultados": [],
                "clasificacion": [],
                "historial": [],
                "temporadas": [],
                "puntos": [],
                "palmares": [],
                "sistema_ligas": [],
            },
            "publicidad": {
                "seccion": False,
                "calendario": False,
                "resultados": False,
                "clasificacion": False,
                "historial": False,
                "temporadas": False,
                "puntos": False,
                "palmares": False,
                "sistema_ligas": False,
            },
            "patrocinador": {
                "seccion": None,
                "calendario": None,
                "resultados": None,
                "clasificacion": None,
                "historial": None,
                "temporadas": None,
                "puntos": None,
                "palmares": None,
                "sistema_ligas": None,
            },
        },
    "valladolid": {
            "amazon": {
                "seccion": [
                ],
                "calendario": [],
                "resultados": [],
                "clasificacion": [],
                "historial": [],
                "temporadas": [],
                "puntos": [],
                "palmares": [],
                "sistema_ligas": [],
            },
            "publicidad": {
                "seccion": False,
                "calendario": False,
                "resultados": False,
                "clasificacion": False,
                "historial": False,
                "temporadas": False,
                "puntos": False,
                "palmares": False,
                "sistema_ligas": False,
            },
            "patrocinador": {
                "seccion": None,
                "calendario": None,
                "resultados": None,
                "clasificacion": None,
                "historial": None,
                "temporadas": None,
                "puntos": None,
                "palmares": None,
                "sistema_ligas": None,
            },
        },
    "rv_fem": {
            "amazon": {
                "seccion": [
                ],
                "calendario": [],
                "resultados": [],
                "clasificacion": [],
                "historial": [],
                "temporadas": [],
                "puntos": [],
                "palmares": [],
                "sistema_ligas": [],
            },
            "publicidad": {
                "seccion": False,
                "calendario": False,
                "resultados": False,
                "clasificacion": False,
                "historial": False,
                "temporadas": False,
                "puntos": False,
                "palmares": False,
                "sistema_ligas": False,
            },
            "patrocinador": {
                "seccion": None,
                "calendario": None,
                "resultados": None,
                "clasificacion": None,
                "historial": None,
                "temporadas": None,
                "puntos": None,
                "palmares": None,
                "sistema_ligas": None,
            },
        },
    "promesas": {
            "amazon": {
                "seccion": [
                ],
                "calendario": [],
                "resultados": [],
                "clasificacion": [],
                "historial": [],
                "temporadas": [],
                "puntos": [],
                "palmares": [],
                "sistema_ligas": [],
            },
            "publicidad": {
                "seccion": False,
                "calendario": False,
                "resultados": False,
                "clasificacion": False,
                "historial": False,
                "temporadas": False,
                "puntos": False,
                "palmares": False,
                "sistema_ligas": False,
            },
            "patrocinador": {
                "seccion": None,
                "calendario": None,
                "resultados": None,
                "clasificacion": None,
                "historial": None,
                "temporadas": None,
                "puntos": None,
                "palmares": None,
                "sistema_ligas": None,
            },
        },
    "parquesol": {
            "amazon": {
                "seccion": [
                ],
                "calendario": [],
                "resultados": [],
                "clasificacion": [],
                "historial": [],
                "temporadas": [],
                "puntos": [],
                "palmares": [],
                "sistema_ligas": [],
            },
            "publicidad": {
                "seccion": False,
                "calendario": False,
                "resultados": False,
                "clasificacion": False,
                "historial": False,
                "temporadas": False,
                "puntos": False,
                "palmares": False,
                "sistema_ligas": False,
            },
            "patrocinador": {
                "seccion": None,
                "calendario": None,
                "resultados": None,
                "clasificacion": None,
                "historial": None,
                "temporadas": None,
                "puntos": None,
                "palmares": None,
                "sistema_ligas": None,
            },
        },
    "galvan": {
            "amazon": {
                "seccion": [
                ],
                "calendario": [],
                "resultados": [],
                "clasificacion": [],
                "historial": [],
                "temporadas": [],
                "puntos": [],
                "palmares": [],
                "sistema_ligas": [],
            },
            "publicidad": {
                "seccion": False,
                "calendario": False,
                "resultados": False,
                "clasificacion": False,
                "historial": False,
                "temporadas": False,
                "puntos": False,
                "palmares": False,
                "sistema_ligas": False,
            },
            "patrocinador": {
                "seccion": None,
                "calendario": None,
                "resultados": None,
                "clasificacion": None,
                "historial": None,
                "temporadas": None,
                "puntos": None,
                "palmares": None,
                "sistema_ligas": None,
            },
        },
    "vall_sala": {
            "amazon": {
                "seccion": [
                ],
                "calendario": [],
                "resultados": [],
                "clasificacion": [],
                "historial": [],
                "temporadas": [],
                "puntos": [],
                "palmares": [],
                "sistema_ligas": [],
            },
            "publicidad": {
                "seccion": False,
                "calendario": False,
                "resultados": False,
                "clasificacion": False,
                "historial": False,
                "temporadas": False,
                "puntos": False,
                "palmares": False,
                "sistema_ligas": False,
            },
            "patrocinador": {
                "seccion": None,
                "calendario": None,
                "resultados": None,
                "clasificacion": None,
                "historial": None,
                "temporadas": None,
                "puntos": None,
                "palmares": None,
                "sistema_ligas": None,
            },
        },
    "caja": {
            "amazon": {
                "seccion": [
                ],
                "calendario": [],
                "resultados": [],
                "clasificacion": [],
                "historial": [],
                "temporadas": [],
                "puntos": [],
                "palmares": [],
                "sistema_ligas": [],
            },
            "publicidad": {
                "seccion": False,
                "calendario": False,
                "resultados": False,
                "clasificacion": False,
                "historial": False,
                "temporadas": False,
                "puntos": False,
                "palmares": False,
                "sistema_ligas": False,
            },
            "patrocinador": {
                "seccion": None,
                "calendario": None,
                "resultados": None,
                "clasificacion": None,
                "historial": None,
                "temporadas": None,
                "puntos": None,
                "palmares": None,
                "sistema_ligas": None,
            },
        },
    "panteras": {
            "amazon": {
                "seccion": [
                ],
                "calendario": [],
                "resultados": [],
                "clasificacion": [],
                "historial": [],
                "temporadas": [],
                "puntos": [],
                "palmares": [],
                "sistema_ligas": [],
            },
            "publicidad": {
                "seccion": False,
                "calendario": False,
                "resultados": False,
                "clasificacion": False,
                "historial": False,
                "temporadas": False,
                "puntos": False,
                "palmares": False,
                "sistema_ligas": False,
            },
            "patrocinador": {
                "seccion": None,
                "calendario": None,
                "resultados": None,
                "clasificacion": None,
                "historial": None,
                "temporadas": None,
                "puntos": None,
                "palmares": None,
                "sistema_ligas": None,
            },
        },
    "vrac": {
            "amazon": {
                "seccion": [
                ],
                "calendario": [],
                "resultados": [],
                "clasificacion": [],
                "historial": [],
                "temporadas": [],
                "puntos": [],
                "palmares": [],
                "sistema_ligas": [],
            },
            "publicidad": {
                "seccion": False,
                "calendario": False,
                "resultados": False,
                "clasificacion": False,
                "historial": False,
                "temporadas": False,
                "puntos": False,
                "palmares": False,
                "sistema_ligas": False,
            },
            "patrocinador": {
                "seccion": None,
                "calendario": None,
                "resultados": None,
                "clasificacion": None,
                "historial": None,
                "temporadas": None,
                "puntos": None,
                "palmares": None,
                "sistema_ligas": None,
            },
        },
    "salvador": {
            "amazon": {
                "seccion": [
                ],
                "calendario": [],
                "resultados": [],
                "clasificacion": [],
                "historial": [],
                "temporadas": [],
                "puntos": [],
                "palmares": [],
                "sistema_ligas": [],
            },
            "publicidad": {
                "seccion": False,
                "calendario": False,
                "resultados": False,
                "clasificacion": False,
                "historial": False,
                "temporadas": False,
                "puntos": False,
                "palmares": False,
                "sistema_ligas": False,
            },
            "patrocinador": {
                "seccion": None,
                "calendario": None,
                "resultados": None,
                "clasificacion": None,
                "historial": None,
                "temporadas": None,
                "puntos": None,
                "palmares": None,
                "sistema_ligas": None,
            },
        },
    "salvador_fem": {
            "amazon": {
                "seccion": [
                ],
                "calendario": [],
                "resultados": [],
                "clasificacion": [],
                "historial": [],
                "temporadas": [],
                "puntos": [],
                "palmares": [],
                "sistema_ligas": [],
            },
            "publicidad": {
                "seccion": False,
                "calendario": False,
                "resultados": False,
                "clasificacion": False,
                "historial": False,
                "temporadas": False,
                "puntos": False,
                "palmares": False,
                "sistema_ligas": False,
            },
            "patrocinador": {
                "seccion": None,
                "calendario": None,
                "resultados": None,
                "clasificacion": None,
                "historial": None,
                "temporadas": None,
                "puntos": None,
                "palmares": None,
                "sistema_ligas": None,
            },
        },
    "vcv": {
        "amazon": {
            "seccion": [
            ],
            "calendario": [],
            "resultados": [],
            "clasificacion": [],
            "historial": [],
            "temporadas": [],
            "puntos": [],
            "palmares": [],
            "sistema_ligas": [],
        },
        "publicidad": {
            "seccion": False,
            "calendario": False,
            "resultados": False,
            "clasificacion": False,
            "historial": False,
            "temporadas": False,
            "puntos": False,
            "palmares": False,
            "sistema_ligas": False,
        },
        "patrocinador": {
            "seccion": None,
            "calendario": None,
            "resultados": None,
            "clasificacion": None,
            "historial": None,
            "temporadas": None,
            "puntos": None,
            "palmares": None,
            "sistema_ligas": None,
        },
    },
    "san_jose": {
            "amazon": {
                "seccion": [
                ],
                "calendario": [],
                "resultados": [],
                "clasificacion": [],
                "historial": [],
                "temporadas": [],
                "puntos": [],
                "palmares": [],
                "sistema_ligas": [],
            },
            "publicidad": {
                "seccion": False,
                "calendario": False,
                "resultados": False,
                "clasificacion": False,
                "historial": False,
                "temporadas": False,
                "puntos": False,
                "palmares": False,
                "sistema_ligas": False,
            },
            "patrocinador": {
                "seccion": None,
                "calendario": None,
                "resultados": None,
                "clasificacion": None,
                "historial": None,
                "temporadas": None,
                "puntos": None,
                "palmares": None,
                "sistema_ligas": None,
            },
        },
}