COMERCIAL = {
    "uemc": {
        "amazon": {
            "seccion": [{
                "titulo": "SENSTON Balón de Baloncesto Adulto",
                "descripcion": "Balón de tamaño 7 Interior, exterior para adultos. Resistente al desgaste, con excelente agarre y control estable.",
                "imagen": "balon-senston.webp",
                "alt": "SENSTON Balón de baloncesto Adulto",
                "url": "https://link.amazon/B0bPncsTk"
            }],
            "calendario": [],
            "resultados": [],
            "clasificacion": [],
            "historial": [],
            "temporadas": [],
            "puntos": [],
            "palmares": [],
            "sistema_ligas": [],
        },
        "publicidad": {
            "seccion": False,
            "calendario": False,
            "resultados": False,
            "clasificacion": False,
            "historial": False,
            "temporadas": False,
            "puntos": False,
            "palmares": False,
            "sistema_ligas": False,
        },
        "patrocinador": {
            "seccion": None,
            "calendario": None,
            "resultados": None,
            "clasificacion": None,
            "historial": None,
            "temporadas": None,
            "puntos": None,
            "palmares": None,
            "sistema_ligas": None,
        },
    },
    "ponce": {
        "amazon": {
            "seccion": [{
                "titulo": "YAHEETECH Canasta de Baloncesto",
                "descripcion": "Canasta para exteriores portátil, altura ajustable 182-213 cm. Con ruedas, base de lastre, para niños y adultos.",
                "imagen": "canasta-ext.webp",
                "alt": "YAHEETECH Canasta de baloncesto",
                "url": "https://link.amazon/B0f0HOi4Z"
            }],
            "calendario": [],
            "resultados": [],
            "clasificacion": [],
            "historial": [],
            "temporadas": [],
            "puntos": [],
            "palmares": [],
            "sistema_ligas": [],
        },
        "publicidad": {
            "seccion": False,
            "calendario": False,
            "resultados": False,
            "clasificacion": False,
            "historial": False,
            "temporadas": False,
            "puntos": False,
            "palmares": False,
            "sistema_ligas": False,
        },
        "patrocinador": {
            "seccion": None,
            "calendario": None,
            "resultados": None,
            "clasificacion": None,
            "historial": None,
            "temporadas": None,
            "puntos": None,
            "palmares": None,
            "sistema_ligas": None,
        },
    },
    "aliados": {
        "amazon": {
            "seccion": [{
                "titulo": "FILA Marked Flow Mujer",
                "descripcion": "Zapatillas baloncesto mujer, con amortiguación alta y suela antideslizante. Transpirables para entrenamientos y competición.",
                "imagen": "zapatillas-fila.webp",
                "alt": "FILA Marked Flow Mujer",
                "url": "https://link.amazon/B0czi71Lb"
            }],
            "calendario": [],
            "resultados": [],
            "clasificacion": [],
            "historial": [],
            "temporadas": [],
            "puntos": [],
            "palmares": [],
            "sistema_ligas": [],
        },
        "publicidad": {
            "seccion": False,
            "calendario": False,
            "resultados": False,
            "clasificacion": False,
            "historial": False,
            "temporadas": False,
            "puntos": False,
            "palmares": False,
            "sistema_ligas": False,
        },
        "patrocinador": {
            "seccion": None,
            "calendario": None,
            "resultados": None,
            "clasificacion": None,
            "historial": None,
            "temporadas": None,
            "puntos": None,
            "palmares": None,
            "sistema_ligas": None,
        },
    },
    "aula": {
        "amazon": {
            "seccion": [{
                "titulo": "HUMMEL hmlCLASSIC EnergizerHB",
                "descripcion": "Balón de balonmano oficial, tamaño 3, para adultos y jóvenes. Con superficie de goma antideslizante y duradera.",
                "imagen": "balon-balonmano.webp",
                "alt": "HUMMEL hmlCLASSIC EnergizerHB",
                "url": "https://link.amazon/B0czi71Lb"
            }],
            "calendario": [],
            "resultados": [],
            "clasificacion": [],
            "historial": [],
            "temporadas": [],
            "puntos": [],
            "palmares": [],
            "sistema_ligas": [],
        },
        "publicidad": {
            "seccion": False,
            "calendario": False,
            "resultados": False,
            "clasificacion": False,
            "historial": False,
            "temporadas": False,
            "puntos": False,
            "palmares": False,
            "sistema_ligas": False,
        },
        "patrocinador": {
            "seccion": None,
            "calendario": None,
            "resultados": None,
            "clasificacion": None,
            "historial": None,
            "temporadas": None,
            "puntos": None,
            "palmares": None,
            "sistema_ligas": None,
        },
    },
    "recoletas": {
        "amazon": {
            "seccion": [{
                "titulo": "EULANT Rodilleras",
                "descripcion": "Usables para la mayoría de deportes, como balonmano, voleibol, baloncesto y fútbol. Con espuma de alta densidad para protección y comodidad.",
                "imagen": "balon-balonmano.webp",
                "alt": "EULANT Rodilleras",
                "url": "https://link.amazon/B010B94ym"
            }],
            "calendario": [],
            "resultados": [],
            "clasificacion": [],
            "historial": [],
            "temporadas": [],
            "puntos": [],
            "palmares": [],
            "sistema_ligas": [],
        },
        "publicidad": {
            "seccion": False,
            "calendario": False,
            "resultados": False,
            "clasificacion": False,
            "historial": False,
            "temporadas": False,
            "puntos": False,
            "palmares": False,
            "sistema_ligas": False,
        },
        "patrocinador": {
            "seccion": None,
            "calendario": None,
            "resultados": None,
            "clasificacion": None,
            "historial": None,
            "temporadas": None,
            "puntos": None,
            "palmares": None,
            "sistema_ligas": None,
        },
    },
    "valladolid": {
        "amazon": {
            "seccion": [{
                "titulo": "DUNLOP Porterias Fútbol",
                "descripcion": "Juego de 2 mini porterías plegables de fútbol de 44x44cm, Kit de entrenamiento para niños y adultos, interior y exterior. ",
                "imagen": "porterias.webp",
                "alt": "DUNLOP Porterias Fútbol",
                "url": "https://link.amazon/B0dFkS0Rg"
            }],
            "calendario": [],
            "resultados": [],
            "clasificacion": [],
            "historial": [],
            "temporadas": [],
            "puntos": [],
            "palmares": [],
            "sistema_ligas": [],
        },
        "publicidad": {
            "seccion": False,
            "calendario": False,
            "resultados": False,
            "clasificacion": False,
            "historial": False,
            "temporadas": False,
            "puntos": False,
            "palmares": False,
            "sistema_ligas": False,
        },
        "patrocinador": {
            "seccion": None,
            "calendario": None,
            "resultados": None,
            "clasificacion": None,
            "historial": None,
            "temporadas": None,
            "puntos": None,
            "palmares": None,
            "sistema_ligas": None,
        },
    },
    "rv_fem": {
        "amazon": {
            "seccion": [{
                "titulo": "BEAST RAGE Guantes de portero niño",
                "descripcion": "Guantes de portero para niños y jóvenes, con agarre y protección. Ideales para entrenamientos y partidos de fútbol.",
                "imagen": "guantes.webp",
                "alt": "BEAST RAGE Guantes de portero niño",
                "url": "https://link.amazon/B0evnPp8S"
            }],
            "calendario": [],
            "resultados": [],
            "clasificacion": [],
            "historial": [],
            "temporadas": [],
            "puntos": [],
            "palmares": [],
            "sistema_ligas": [],
        },
        "publicidad": {
            "seccion": False,
            "calendario": False,
            "resultados": False,
            "clasificacion": False,
            "historial": False,
            "temporadas": False,
            "puntos": False,
            "palmares": False,
            "sistema_ligas": False,
        },
        "patrocinador": {
            "seccion": None,
            "calendario": None,
            "resultados": None,
            "clasificacion": None,
            "historial": None,
            "temporadas": None,
            "puntos": None,
            "palmares": None,
            "sistema_ligas": None,
        },
    },
    "promesas": {
        "amazon": {
            "seccion": [{
                "titulo": "HY-PRO Uefa Champions League Fútbol",
                "descripcion": "Balón de fútbol oficial de la UEFA Champions League, tamaño 5, cosido a máquina, para entrenamientos y partidos de competición.",
                "imagen": "balonuefa2.webp",
                "alt": "HY-PRO Uefa Champions League Fútbol",
                "url": "https://link.amazon/B09uudoqy"
            }],
            "calendario": [],
            "resultados": [],
            "clasificacion": [],
            "historial": [],
            "temporadas": [],
            "puntos": [],
            "palmares": [],
            "sistema_ligas": [],
        },
        "publicidad": {
            "seccion": False,
            "calendario": False,
            "resultados": False,
            "clasificacion": False,
            "historial": False,
            "temporadas": False,
            "puntos": False,
            "palmares": False,
            "sistema_ligas": False,
        },
        "patrocinador": {
            "seccion": None,
            "calendario": None,
            "resultados": None,
            "clasificacion": None,
            "historial": None,
            "temporadas": None,
            "puntos": None,
            "palmares": None,
            "sistema_ligas": None,
        },
    },
    "tordesillas": {
            "amazon": {
                "seccion": [{
                    "titulo": "GILTEN Mini Espinilleras",
                    "descripcion": "Mini espinilleras para niños y jóvenes estilo minimalista, protección para fútbol y fútbol sala de 12x7,5cm.",
                    "imagen": "espinilleras.webp",
                    "alt": "GILTEN Mini Espinilleras",
                    "url": "https://link.amazon/B00uaF6OY"
                }],
                "calendario": [],
                "resultados": [],
                "clasificacion": [],
                "historial": [],
                "temporadas": [],
                "puntos": [],
                "palmares": [],
                "sistema_ligas": [],
            },
            "publicidad": {
                "seccion": False,
                "calendario": False,
                "resultados": False,
                "clasificacion": False,
                "historial": False,
                "temporadas": False,
                "puntos": False,
                "palmares": False,
                "sistema_ligas": False,
            },
            "patrocinador": {
                "seccion": None,
                "calendario": None,
                "resultados": None,
                "clasificacion": None,
                "historial": None,
                "temporadas": None,
                "puntos": None,
                "palmares": None,
                "sistema_ligas": None,
            },
        },
    "parquesol": {
        "amazon": {
            "seccion": [{
                "titulo": "ROSEFLOWER Pizarra Entrenador Fútbol",
                "descripcion": "Pizarra táctica magnética para entrenadores de fútbol, con rotulador y borrador. Ideal para planificar estrategias y tácticas de juego.",
                "imagen": "entrenador-pizarra.webp",
                "alt": "ROSEFLOWER Pizarra Entrenador Fútbol",
                "url": "https://link.amazon/B078ELFyh"
            }],
            "calendario": [],
            "resultados": [],
            "clasificacion": [],
            "historial": [],
            "temporadas": [],
            "puntos": [],
            "palmares": [],
            "sistema_ligas": [],
        },
        "publicidad": {
            "seccion": False,
            "calendario": False,
            "resultados": False,
            "clasificacion": False,
            "historial": False,
            "temporadas": False,
            "puntos": False,
            "palmares": False,
            "sistema_ligas": False,
        },
        "patrocinador": {
            "seccion": None,
            "calendario": None,
            "resultados": None,
            "clasificacion": None,
            "historial": None,
            "temporadas": None,
            "puntos": None,
            "palmares": None,
            "sistema_ligas": None,
        },
    },
    "valladoliDi": {
        "amazon": {
            "seccion": [{
                "titulo": "GVOLATEE Accesorios Entrenamiento Fútbol",
                "descripcion": "Kit de entrenamiento de fútbol con conos, vallas y escaleras de agilidad. Ideal para mejorar la velocidad, coordinación y habilidades técnicas.",
                "imagen": "acces-entre.webp",
                "alt": "GVOLATEE Accesorios Entrenamiento Fútbol",
                "url": "https://link.amazon/B0i15PbUr"
            }],
            "calendario": [],
            "resultados": [],
            "clasificacion": [],
            "historial": [],
            "temporadas": [],
            "puntos": [],
            "palmares": [],
            "sistema_ligas": [],
        },
        "publicidad": {
            "seccion": False,
            "calendario": False,
            "resultados": False,
            "clasificacion": False,
            "historial": False,
            "temporadas": False,
            "puntos": False,
            "palmares": False,
            "sistema_ligas": False,
        },
        "patrocinador": {
            "seccion": None,
            "calendario": None,
            "resultados": None,
            "clasificacion": None,
            "historial": None,
            "temporadas": None,
            "puntos": None,
            "palmares": None,
            "sistema_ligas": None,
        },
    },
    "galvan": {
        "amazon": {
            "seccion": [{
                "titulo": "KASIAN Balón Fútbol Pro KS444",
                "descripcion": "Balón resistente de alto rendimiento con tecnología Hypercell. Ideal para    entrenamientos y partidos de competición",
                "imagen": "balon-kasian.webp",
                "alt": "KASIAN Balón Fútbol Pro",
                "url": "https://link.amazon/B0enBxFve"
            }],
            "calendario": [],
            "resultados": [],
            "clasificacion": [],
            "historial": [],
            "temporadas": [],
            "puntos": [],
            "palmares": [],
            "sistema_ligas": [],
        },
        "publicidad": {
            "seccion": False,
            "calendario": False,
            "resultados": False,
            "clasificacion": False,
            "historial": False,
            "temporadas": False,
            "puntos": False,
            "palmares": False,
            "sistema_ligas": False,
        },
        "patrocinador": {
            "seccion": None,
            "calendario": None,
            "resultados": None,
            "clasificacion": None,
            "historial": None,
            "temporadas": None,
            "puntos": None,
            "palmares": None,
            "sistema_ligas": None,
        },
    },
    "vall_sala": {
        "amazon": {
            "seccion": [{
                "titulo": "Bolsa Unisex deportiva OSFA",
                "descripcion": "Bolsa de deporte ligera y duradera, ideal para llevar tus pertenencias al gimnasio o a tus actividades deportivas.",
                "imagen": "bolsa_futsal.webp",
                "alt": "Bolsa Unisex deportiva OSFA",
                "url": "https://link.amazon/B0iWBEGMy"
            }],
            "calendario": [],
            "resultados": [],
            "clasificacion": [],
            "historial": [],
            "temporadas": [],
            "puntos": [],
            "palmares": [],
            "sistema_ligas": [],
        },
        "publicidad": {
            "seccion": False,
            "calendario": False,
            "resultados": False,
            "clasificacion": False,
            "historial": False,
            "temporadas": False,
            "puntos": False,
            "palmares": False,
            "sistema_ligas": False,
        },
        "patrocinador": {
            "seccion": None,
            "calendario": None,
            "resultados": None,
            "clasificacion": None,
            "historial": None,
            "temporadas": None,
            "puntos": None,
            "palmares": None,
            "sistema_ligas": None,
        },
    },
    "caja": {
        "amazon": {
            "seccion": [{
                "titulo": "JHDZ Ganchos Colgadores Hockey ",
                "descripcion": "Ganchos colgadores de hockey para organizar y almacenar tu ropa de hockey de manera eficiente, de 5 ganchos y portatil",
                "imagen": "perche-hockey.webp",
                "alt": "JHDZ Ganchos Colgadores Hockey",
                "url": "https://link.amazon/B0fFlBNhl"
            }],
            "calendario": [],
            "resultados": [],
            "clasificacion": [],
            "historial": [],
            "temporadas": [],
            "puntos": [],
            "palmares": [],
            "sistema_ligas": [],
        },
        "publicidad": {
            "seccion": False,
            "calendario": False,
            "resultados": False,
            "clasificacion": False,
            "historial": False,
            "temporadas": False,
            "puntos": False,
            "palmares": False,
            "sistema_ligas": False,
        },
        "patrocinador": {
            "seccion": None,
            "calendario": None,
            "resultados": None,
            "clasificacion": None,
            "historial": None,
            "temporadas": None,
            "puntos": None,
            "palmares": None,
            "sistema_ligas": None,
        },
    },
    "panteras": {
        "amazon": {
            "seccion": [{
                "titulo": "BAUER XR Patines Hockey Línea",
                "descripcion": "Patines de hockey en línea para adultos, con ruedas de alta calidad y diseño ergonómico para un rendimiento óptimo en la pista.",
                "imagen": "patines.webp",
                "alt": "BAUER XR Patines Hockey Línea",
                "url": "https://link.amazon/B0jebIpIk"
            }],
            "calendario": [],
            "resultados": [],
            "clasificacion": [],
            "historial": [],
            "temporadas": [],
            "puntos": [],
            "palmares": [],
            "sistema_ligas": [],
        },
        "publicidad": {
            "seccion": False,
            "calendario": False,
            "resultados": False,
            "clasificacion": False,
            "historial": False,
            "temporadas": False,
            "puntos": False,
            "palmares": False,
            "sistema_ligas": False,
        },
        "patrocinador": {
            "seccion": None,
            "calendario": None,
            "resultados": None,
            "clasificacion": None,
            "historial": None,
            "temporadas": None,
            "puntos": None,
            "palmares": None,
            "sistema_ligas": None,
        },
    },
    "vrac": {
        "amazon": {
            "seccion": [{
                "titulo": "OPRO Protector Bucal Rugby",
                "descripcion": "Protector bucal de rugby para protección durante los partidos y entrenamientos, excelente comodidad, protección y ajuste.",
                "imagen": "prot-bucal.webp",
                "alt": "OPRO Protector Bucal Rugby",
                "url": "https://link.amazon/B03FKQQ4k"
            }],
            "calendario": [],
            "resultados": [],
            "clasificacion": [],
            "historial": [],
            "temporadas": [],
            "puntos": [],
            "palmares": [],
            "sistema_ligas": [],
        },
        "publicidad": {
            "seccion": False,
            "calendario": False,
            "resultados": False,
            "clasificacion": False,
            "historial": False,
            "temporadas": False,
            "puntos": False,
            "palmares": False,
            "sistema_ligas": False,
        },
        "patrocinador": {
            "seccion": None,
            "calendario": None,
            "resultados": None,
            "clasificacion": None,
            "historial": None,
            "temporadas": None,
            "puntos": None,
            "palmares": None,
            "sistema_ligas": None,
        },
    },
    "salvador": {
        "amazon": {
            "seccion": [{
                "titulo": "GILBERT RUGBY Lampara de mesita",
                "descripcion": "Lámpara de noche original de pelota de rugby, luz de escritorio. Ideal para decoración de dormitorio, sala de estar y oficina.",
                "imagen": "lampara-rugby.webp",
                "alt": "GILBERT RUGBY Lampara de mesita",
                "url": "https://link.amazon/B07DpFYDA"
            }],
            "calendario": [],
            "resultados": [],
            "clasificacion": [],
            "historial": [],
            "temporadas": [],
            "puntos": [],
            "palmares": [],
            "sistema_ligas": [],
        },
        "publicidad": {
            "seccion": False,
            "calendario": False,
            "resultados": False,
            "clasificacion": False,
            "historial": False,
            "temporadas": False,
            "puntos": False,
            "palmares": False,
            "sistema_ligas": False,
        },
        "patrocinador": {
            "seccion": None,
            "calendario": None,
            "resultados": None,
            "clasificacion": None,
            "historial": None,
            "temporadas": None,
            "puntos": None,
            "palmares": None,
            "sistema_ligas": None,
        },
    },
    "salvador_fem": {
        "amazon": {
            "seccion": [{
                "titulo": "PHOENIX RAZE Bota Rugby Niño",
                "descripcion": "Botas de rugby para niños duradera y atemperal. Ajuste regularpara el jugador de todo terreno.",
                "imagen": "botas-rugby.webp",
                "alt": "PHOENIX RAZE Bota Rugby Niño",
                "url": "https://link.amazon/B0emBL5ir"
            }],
            "calendario": [],
            "resultados": [],
            "clasificacion": [],
            "historial": [],
            "temporadas": [],
            "puntos": [],
            "palmares": [],
            "sistema_ligas": [],
        },
        "publicidad": {
            "seccion": False,
            "calendario": False,
            "resultados": False,
            "clasificacion": False,
            "historial": False,
            "temporadas": False,
            "puntos": False,
            "palmares": False,
            "sistema_ligas": False,
        },
        "patrocinador": {
            "seccion": None,
            "calendario": None,
            "resultados": None,
            "clasificacion": None,
            "historial": None,
            "temporadas": None,
            "puntos": None,
            "palmares": None,
            "sistema_ligas": None,
        },
    },
    "vcv": {
        "amazon": {
            "seccion": [{
                "titulo": "MIZUNO Mangas Voleibol",
                "descripcion": "Mangas de voleibol de alta calidad y unisex .",
                "imagen": "manguito.webp",
                "alt": "MIZUNO Mangas Voleibol",
                "url": "https://link.amazon/B00nBY77g"
            }],
            "calendario": [],
            "resultados": [],
            "clasificacion": [],
            "historial": [],
            "temporadas": [],
            "puntos": [],
            "palmares": [],
            "sistema_ligas": [],
        },
        "publicidad": {
            "seccion": False,
            "calendario": False,
            "resultados": False,
            "clasificacion": False,
            "historial": False,
            "temporadas": False,
            "puntos": False,
            "palmares": False,
            "sistema_ligas": False,
        },
        "patrocinador": {
            "seccion": None,
            "calendario": None,
            "resultados": None,
            "clasificacion": None,
            "historial": None,
            "temporadas": None,
            "puntos": None,
            "palmares": None,
            "sistema_ligas": None,
        },
    },
    "vacceas": {
            "amazon": {
                "seccion": [{
                    "titulo": "MONDO Pelota Voleibol Niño",
                    "descripcion": "Pelota de voleibol para niños, tamaño 5, ligera y resistente. Ideal todo tipo de superficie, tanto exterior como interior.",
                    "imagen": "balon-voley.webp",
                    "alt": "MONDO Pelota Voleibol Niño",
                    "url": "https://link.amazon/B07Tfv0LU"
                }],
                "calendario": [],
                "resultados": [],
                "clasificacion": [],
                "historial": [],
                "temporadas": [],
                "puntos": [],
                "palmares": [],
                "sistema_ligas": [],
            },
            "publicidad": {
                "seccion": False,
                "calendario": False,
                "resultados": False,
                "clasificacion": False,
                "historial": False,
                "temporadas": False,
                "puntos": False,
                "palmares": False,
                "sistema_ligas": False,
            },
            "patrocinador": {
                "seccion": None,
                "calendario": None,
                "resultados": None,
                "clasificacion": None,
                "historial": None,
                "temporadas": None,
                "puntos": None,
                "palmares": None,
                "sistema_ligas": None,
            },
        },
    "valcyl": {
            "amazon": {
                "seccion": [{
                    "titulo": "NEWBYINN Red de Rebote Voleibol",
                    "descripcion": "Equipo de entrenamiento de voleibol con red de rebote, ideal para mejorar la técnica, con 5 ángulos de rebote ajustable, 7x4cm.",
                    "imagen": "red-voley.webp",
                    "alt": "NEWBYINN Red de Rebote Voleibol",
                    "url": "https://link.amazon/B037fFEXe"
                }],
                "calendario": [],
                "resultados": [],
                "clasificacion": [],
                "historial": [],
                "temporadas": [],
                "puntos": [],
                "palmares": [],
                "sistema_ligas": [],
            },
            "publicidad": {
                "seccion": False,
                "calendario": False,
                "resultados": False,
                "clasificacion": False,
                "historial": False,
                "temporadas": False,
                "puntos": False,
                "palmares": False,
                "sistema_ligas": False,
            },
            "patrocinador": {
                "seccion": None,
                "calendario": None,
                "resultados": None,
                "clasificacion": None,
                "historial": None,
                "temporadas": None,
                "puntos": None,
                "palmares": None,
                "sistema_ligas": None,
            },
        },    
    "san_jose": {
        "amazon": {
            "seccion": [{
                "titulo": "FLINTRONIC Rodilleras Voleibol",
                "descripcion": "Protección para la rodilla, esponja eva de 20mm de grosor, antideslizante para rodillas voleibol, ajustables",
                "imagen": "rodilleras.webp",
                "alt": "FLINTRONIC Rodilleras Voleibol",
                "url": "https://link.amazon/B0hEw1BLp"
            }],
            "calendario": [],
            "resultados": [],
            "clasificacion": [],
            "historial": [],
            "temporadas": [],
            "puntos": [],
            "palmares": [],
            "sistema_ligas": [],
        },
        "publicidad": {
            "seccion": False,
            "calendario": False,
            "resultados": False,
            "clasificacion": False,
            "historial": False,
            "temporadas": False,
            "puntos": False,
            "palmares": False,
            "sistema_ligas": False,
        },
        "patrocinador": {
            "seccion": None,
            "calendario": None,
            "resultados": None,
            "clasificacion": None,
            "historial": None,
            "temporadas": None,
            "puntos": None,
            "palmares": None,
            "sistema_ligas": None,
        },
    },
}
