COMERCIAL = {
    "uemc": {
        "amazon": {
            "seccion": [
                {
                    "titulo": "Balones de baloncesto",
                    "descripcion": "Balones para entrenamiento y juego.",
                    "imagen": "balon-baloncesto.jpg",
                    "alt": "Balón de baloncesto",
                    "url": "#",
                },
                {
                    "titulo": "Zapatillas de baloncesto",
                    "descripcion": "Calzado deportivo para jugar y entrenar.",
                    "imagen": "zapatillas-basket.jpg",
                    "alt": "Zapatillas de baloncesto",
                    "url": "#",
                },
            ],
            "calendario": [],
            "resultados": [],
            "clasificacion": [],
            "historial": [],
            "temporadas": [],
            "puntos": [],
            "palmares": [],
            "sistema_ligas": [],
        },
        "publicidad": {
            "seccion": False,
            "calendario": False,
            "resultados": False,
            "clasificacion": False,
            "historial": False,
            "temporadas": False,
            "puntos": False,
            "palmares": False,
            "sistema_ligas": False,
        },
        "patrocinador": {
            "seccion": {
                "nombre": "Biopiñón S.L.",
                "logo": "biopiñon.png",
                "descripcion": "Empresa colaboradora de deportesdelaciudad",
                "url": "https://www.biopiñon.com",
            },
            "calendario": None,
            "resultados": None,
            "clasificacion": None,
            "historial": None,
            "temporadas": None,
            "puntos": None,
            "palmares": None,
            "sistema_ligas": None,
        },
    },
    "ponce": {
            "amazon": {
                "seccion": [
                    {
                        "titulo": "Balones de baloncesto",
                        "descripcion": "Balones para entrenamiento y juego.",
                        "imagen": "balon-baloncesto.jpg",
                        "alt": "Balón de baloncesto",
                        "url": "#",
                    },
                    {
                        "titulo": "Zapatillas de baloncesto",
                        "descripcion": "Calzado deportivo para jugar y entrenar.",
                        "imagen": "zapatillas-basket.jpg",
                        "alt": "Zapatillas de baloncesto",
                        "url": "#",
                    },
                ],
                "calendario": [],
                "resultados": [],
                "clasificacion": [],
                "historial": [],
                "temporadas": [],
                "puntos": [],
                "palmares": [],
                "sistema_ligas": [],
            },
            "publicidad": {
                "seccion": False,
                "calendario": False,
                "resultados": False,
                "clasificacion": False,
                "historial": False,
                "temporadas": False,
                "puntos": False,
                "palmares": False,
                "sistema_ligas": False,
            },
            "patrocinador": {
                "seccion": None,
                "calendario": None,
                "resultados": None,
                "clasificacion": None,
                "historial": None,
                "temporadas": None,
                "puntos": None,
                "palmares": None,
                "sistema_ligas": None,
            },
        },
    "cdsi": {
            "amazon": {
                "seccion": [
                    {
                        "titulo": "Balones de baloncesto",
                        "descripcion": "Balones para entrenamiento y juego.",
                        "imagen": "balon-baloncesto.jpg",
                        "alt": "Balón de baloncesto",
                        "url": "#",
                    },
                    {
                        "titulo": "Zapatillas de baloncesto",
                        "descripcion": "Calzado deportivo para jugar y entrenar.",
                        "imagen": "zapatillas-basket.jpg",
                        "alt": "Zapatillas de baloncesto",
                        "url": "#",
                    },
                ],
                "calendario": [],
                "resultados": [],
                "clasificacion": [],
                "historial": [],
                "temporadas": [],
                "puntos": [],
                "palmares": [],
                "sistema_ligas": [],
            },
            "publicidad": {
                "seccion": False,
                "calendario": False,
                "resultados": False,
                "clasificacion": False,
                "historial": False,
                "temporadas": False,
                "puntos": False,
                "palmares": False,
                "sistema_ligas": False,
            },
            "patrocinador": {
                "seccion": None,
                "calendario": None,
                "resultados": None,
                "clasificacion": None,
                "historial": None,
                "temporadas": None,
                "puntos": None,
                "palmares": None,
                "sistema_ligas": None,
            },
        },
    "aliados": {
            "amazon": {
                "seccion": [
                    {
                        "titulo": "Balones de baloncesto",
                        "descripcion": "Balones para entrenamiento y juego.",
                        "imagen": "balon-baloncesto.jpg",
                        "alt": "Balón de baloncesto",
                        "url": "#",
                    },
                    {
                        "titulo": "Zapatillas de baloncesto",
                        "descripcion": "Calzado deportivo para jugar y entrenar.",
                        "imagen": "zapatillas-basket.jpg",
                        "alt": "Zapatillas de baloncesto",
                        "url": "#",
                    },
                ],
                "calendario": [],
                "resultados": [],
                "clasificacion": [],
                "historial": [],
                "temporadas": [],
                "puntos": [],
                "palmares": [],
                "sistema_ligas": [],
            },
            "publicidad": {
                "seccion": False,
                "calendario": False,
                "resultados": False,
                "clasificacion": False,
                "historial": False,
                "temporadas": False,
                "puntos": False,
                "palmares": False,
                "sistema_ligas": False,
            },
            "patrocinador": {
                "seccion": None,
                "calendario": None,
                "resultados": None,
                "clasificacion": None,
                "historial": None,
                "temporadas": None,
                "puntos": None,
                "palmares": None,
                "sistema_ligas": None,
            },
        },
    "aula": {
            "amazon": {
                "seccion": [
                    {
                        "titulo": "Balones de baloncesto",
                        "descripcion": "Balones para entrenamiento y juego.",
                        "imagen": "balon-baloncesto.jpg",
                        "alt": "Balón de baloncesto",
                        "url": "#",
                    },
                    {
                        "titulo": "Zapatillas de baloncesto",
                        "descripcion": "Calzado deportivo para jugar y entrenar.",
                        "imagen": "zapatillas-basket.jpg",
                        "alt": "Zapatillas de baloncesto",
                        "url": "#",
                    },
                ],
                "calendario": [],
                "resultados": [],
                "clasificacion": [],
                "historial": [],
                "temporadas": [],
                "puntos": [],
                "palmares": [],
                "sistema_ligas": [],
            },
            "publicidad": {
                "seccion": False,
                "calendario": False,
                "resultados": False,
                "clasificacion": False,
                "historial": False,
                "temporadas": False,
                "puntos": False,
                "palmares": False,
                "sistema_ligas": False,
            },
            "patrocinador": {
                "seccion": None,
                "calendario": None,
                "resultados": None,
                "clasificacion": None,
                "historial": None,
                "temporadas": None,
                "puntos": None,
                "palmares": None,
                "sistema_ligas": None,
            },
        },
    "recoletas": {
            "amazon": {
                "seccion": [
                    {
                        "titulo": "Balones de baloncesto",
                        "descripcion": "Balones para entrenamiento y juego.",
                        "imagen": "balon-baloncesto.jpg",
                        "alt": "Balón de baloncesto",
                        "url": "#",
                    },
                    {
                        "titulo": "Zapatillas de baloncesto",
                        "descripcion": "Calzado deportivo para jugar y entrenar.",
                        "imagen": "zapatillas-basket.jpg",
                        "alt": "Zapatillas de baloncesto",
                        "url": "#",
                    },
                ],
                "calendario": [],
                "resultados": [],
                "clasificacion": [],
                "historial": [],
                "temporadas": [],
                "puntos": [],
                "palmares": [],
                "sistema_ligas": [],
            },
            "publicidad": {
                "seccion": False,
                "calendario": False,
                "resultados": False,
                "clasificacion": False,
                "historial": False,
                "temporadas": False,
                "puntos": False,
                "palmares": False,
                "sistema_ligas": False,
            },
            "patrocinador": {
                "seccion": None,
                "calendario": None,
                "resultados": None,
                "clasificacion": None,
                "historial": None,
                "temporadas": None,
                "puntos": None,
                "palmares": None,
                "sistema_ligas": None,
            },
        },
    "valladolid": {
            "amazon": {
                "seccion": [
                    {
                        "titulo": "Balones de baloncesto",
                        "descripcion": "Balones para entrenamiento y juego.",
                        "imagen": "balon-baloncesto.jpg",
                        "alt": "Balón de baloncesto",
                        "url": "#",
                    },
                    {
                        "titulo": "Zapatillas de baloncesto",
                        "descripcion": "Calzado deportivo para jugar y entrenar.",
                        "imagen": "zapatillas-basket.jpg",
                        "alt": "Zapatillas de baloncesto",
                        "url": "#",
                    },
                ],
                "calendario": [],
                "resultados": [],
                "clasificacion": [],
                "historial": [],
                "temporadas": [],
                "puntos": [],
                "palmares": [],
                "sistema_ligas": [],
            },
            "publicidad": {
                "seccion": False,
                "calendario": False,
                "resultados": False,
                "clasificacion": False,
                "historial": False,
                "temporadas": False,
                "puntos": False,
                "palmares": False,
                "sistema_ligas": False,
            },
            "patrocinador": {
                "seccion": None,
                "calendario": None,
                "resultados": None,
                "clasificacion": None,
                "historial": None,
                "temporadas": None,
                "puntos": None,
                "palmares": None,
                "sistema_ligas": None,
            },
        },
    "rv_femenino": {
            "amazon": {
                "seccion": [
                    {
                        "titulo": "Balones de baloncesto",
                        "descripcion": "Balones para entrenamiento y juego.",
                        "imagen": "balon-baloncesto.jpg",
                        "alt": "Balón de baloncesto",
                        "url": "#",
                    },
                    {
                        "titulo": "Zapatillas de baloncesto",
                        "descripcion": "Calzado deportivo para jugar y entrenar.",
                        "imagen": "zapatillas-basket.jpg",
                        "alt": "Zapatillas de baloncesto",
                        "url": "#",
                    },
                ],
                "calendario": [],
                "resultados": [],
                "clasificacion": [],
                "historial": [],
                "temporadas": [],
                "puntos": [],
                "palmares": [],
                "sistema_ligas": [],
            },
            "publicidad": {
                "seccion": False,
                "calendario": False,
                "resultados": False,
                "clasificacion": False,
                "historial": False,
                "temporadas": False,
                "puntos": False,
                "palmares": False,
                "sistema_ligas": False,
            },
            "patrocinador": {
                "seccion": None,
                "calendario": None,
                "resultados": None,
                "clasificacion": None,
                "historial": None,
                "temporadas": None,
                "puntos": None,
                "palmares": None,
                "sistema_ligas": None,
            },
        },
    "promesas": {
            "amazon": {
                "seccion": [
                    {
                        "titulo": "Balones de baloncesto",
                        "descripcion": "Balones para entrenamiento y juego.",
                        "imagen": "balon-baloncesto.jpg",
                        "alt": "Balón de baloncesto",
                        "url": "#",
                    },
                    {
                        "titulo": "Zapatillas de baloncesto",
                        "descripcion": "Calzado deportivo para jugar y entrenar.",
                        "imagen": "zapatillas-basket.jpg",
                        "alt": "Zapatillas de baloncesto",
                        "url": "#",
                    },
                ],
                "calendario": [],
                "resultados": [],
                "clasificacion": [],
                "historial": [],
                "temporadas": [],
                "puntos": [],
                "palmares": [],
                "sistema_ligas": [],
            },
            "publicidad": {
                "seccion": False,
                "calendario": False,
                "resultados": False,
                "clasificacion": False,
                "historial": False,
                "temporadas": False,
                "puntos": False,
                "palmares": False,
                "sistema_ligas": False,
            },
            "patrocinador": {
                "seccion": None,
                "calendario": None,
                "resultados": None,
                "clasificacion": None,
                "historial": None,
                "temporadas": None,
                "puntos": None,
                "palmares": None,
                "sistema_ligas": None,
            },
        },
    "parquesol": {
            "amazon": {
                "seccion": [
                    {
                        "titulo": "Balones de baloncesto",
                        "descripcion": "Balones para entrenamiento y juego.",
                        "imagen": "balon-baloncesto.jpg",
                        "alt": "Balón de baloncesto",
                        "url": "#",
                    },
                    {
                        "titulo": "Zapatillas de baloncesto",
                        "descripcion": "Calzado deportivo para jugar y entrenar.",
                        "imagen": "zapatillas-basket.jpg",
                        "alt": "Zapatillas de baloncesto",
                        "url": "#",
                    },
                ],
                "calendario": [],
                "resultados": [],
                "clasificacion": [],
                "historial": [],
                "temporadas": [],
                "puntos": [],
                "palmares": [],
                "sistema_ligas": [],
            },
            "publicidad": {
                "seccion": False,
                "calendario": False,
                "resultados": False,
                "clasificacion": False,
                "historial": False,
                "temporadas": False,
                "puntos": False,
                "palmares": False,
                "sistema_ligas": False,
            },
            "patrocinador": {
                "seccion": None,
                "calendario": None,
                "resultados": None,
                "clasificacion": None,
                "historial": None,
                "temporadas": None,
                "puntos": None,
                "palmares": None,
                "sistema_ligas": None,
            },
        },
    "galvan": {
            "amazon": {
                "seccion": [
                    {
                        "titulo": "Balones de baloncesto",
                        "descripcion": "Balones para entrenamiento y juego.",
                        "imagen": "balon-baloncesto.jpg",
                        "alt": "Balón de baloncesto",
                        "url": "#",
                    },
                    {
                        "titulo": "Zapatillas de baloncesto",
                        "descripcion": "Calzado deportivo para jugar y entrenar.",
                        "imagen": "zapatillas-basket.jpg",
                        "alt": "Zapatillas de baloncesto",
                        "url": "#",
                    },
                ],
                "calendario": [],
                "resultados": [],
                "clasificacion": [],
                "historial": [],
                "temporadas": [],
                "puntos": [],
                "palmares": [],
                "sistema_ligas": [],
            },
            "publicidad": {
                "seccion": False,
                "calendario": False,
                "resultados": False,
                "clasificacion": False,
                "historial": False,
                "temporadas": False,
                "puntos": False,
                "palmares": False,
                "sistema_ligas": False,
            },
            "patrocinador": {
                "seccion": None,
                "calendario": None,
                "resultados": None,
                "clasificacion": None,
                "historial": None,
                "temporadas": None,
                "puntos": None,
                "palmares": None,
                "sistema_ligas": None,
            },
        },
    "vall_sala": {
            "amazon": {
                "seccion": [
                    {
                        "titulo": "Balones de baloncesto",
                        "descripcion": "Balones para entrenamiento y juego.",
                        "imagen": "balon-baloncesto.jpg",
                        "alt": "Balón de baloncesto",
                        "url": "#",
                    },
                    {
                        "titulo": "Zapatillas de baloncesto",
                        "descripcion": "Calzado deportivo para jugar y entrenar.",
                        "imagen": "zapatillas-basket.jpg",
                        "alt": "Zapatillas de baloncesto",
                        "url": "#",
                    },
                ],
                "calendario": [],
                "resultados": [],
                "clasificacion": [],
                "historial": [],
                "temporadas": [],
                "puntos": [],
                "palmares": [],
                "sistema_ligas": [],
            },
            "publicidad": {
                "seccion": False,
                "calendario": False,
                "resultados": False,
                "clasificacion": False,
                "historial": False,
                "temporadas": False,
                "puntos": False,
                "palmares": False,
                "sistema_ligas": False,
            },
            "patrocinador": {
                "seccion": None,
                "calendario": None,
                "resultados": None,
                "clasificacion": None,
                "historial": None,
                "temporadas": None,
                "puntos": None,
                "palmares": None,
                "sistema_ligas": None,
            },
        },
    "caja": {
            "amazon": {
                "seccion": [
                    {
                        "titulo": "Balones de baloncesto",
                        "descripcion": "Balones para entrenamiento y juego.",
                        "imagen": "balon-baloncesto.jpg",
                        "alt": "Balón de baloncesto",
                        "url": "#",
                    },
                    {
                        "titulo": "Zapatillas de baloncesto",
                        "descripcion": "Calzado deportivo para jugar y entrenar.",
                        "imagen": "zapatillas-basket.jpg",
                        "alt": "Zapatillas de baloncesto",
                        "url": "#",
                    },
                ],
                "calendario": [],
                "resultados": [],
                "clasificacion": [],
                "historial": [],
                "temporadas": [],
                "puntos": [],
                "palmares": [],
                "sistema_ligas": [],
            },
            "publicidad": {
                "seccion": False,
                "calendario": False,
                "resultados": False,
                "clasificacion": False,
                "historial": False,
                "temporadas": False,
                "puntos": False,
                "palmares": False,
                "sistema_ligas": False,
            },
            "patrocinador": {
                "seccion": None,
                "calendario": None,
                "resultados": None,
                "clasificacion": None,
                "historial": None,
                "temporadas": None,
                "puntos": None,
                "palmares": None,
                "sistema_ligas": None,
            },
        },
    "panteras": {
            "amazon": {
                "seccion": [
                    {
                        "titulo": "Balones de baloncesto",
                        "descripcion": "Balones para entrenamiento y juego.",
                        "imagen": "balon-baloncesto.jpg",
                        "alt": "Balón de baloncesto",
                        "url": "#",
                    },
                    {
                        "titulo": "Zapatillas de baloncesto",
                        "descripcion": "Calzado deportivo para jugar y entrenar.",
                        "imagen": "zapatillas-basket.jpg",
                        "alt": "Zapatillas de baloncesto",
                        "url": "#",
                    },
                ],
                "calendario": [],
                "resultados": [],
                "clasificacion": [],
                "historial": [],
                "temporadas": [],
                "puntos": [],
                "palmares": [],
                "sistema_ligas": [],
            },
            "publicidad": {
                "seccion": False,
                "calendario": False,
                "resultados": False,
                "clasificacion": False,
                "historial": False,
                "temporadas": False,
                "puntos": False,
                "palmares": False,
                "sistema_ligas": False,
            },
            "patrocinador": {
                "seccion": None,
                "calendario": None,
                "resultados": None,
                "clasificacion": None,
                "historial": None,
                "temporadas": None,
                "puntos": None,
                "palmares": None,
                "sistema_ligas": None,
            },
        },
    "vrac": {
            "amazon": {
                "seccion": [
                    {
                        "titulo": "Balones de baloncesto",
                        "descripcion": "Balones para entrenamiento y juego.",
                        "imagen": "balon-baloncesto.jpg",
                        "alt": "Balón de baloncesto",
                        "url": "#",
                    },
                    {
                        "titulo": "Zapatillas de baloncesto",
                        "descripcion": "Calzado deportivo para jugar y entrenar.",
                        "imagen": "zapatillas-basket.jpg",
                        "alt": "Zapatillas de baloncesto",
                        "url": "#",
                    },
                ],
                "calendario": [],
                "resultados": [],
                "clasificacion": [],
                "historial": [],
                "temporadas": [],
                "puntos": [],
                "palmares": [],
                "sistema_ligas": [],
            },
            "publicidad": {
                "seccion": False,
                "calendario": False,
                "resultados": False,
                "clasificacion": False,
                "historial": False,
                "temporadas": False,
                "puntos": False,
                "palmares": False,
                "sistema_ligas": False,
            },
            "patrocinador": {
                "seccion": None,
                "calendario": None,
                "resultados": None,
                "clasificacion": None,
                "historial": None,
                "temporadas": None,
                "puntos": None,
                "palmares": None,
                "sistema_ligas": None,
            },
        },
    "salvador": {
            "amazon": {
                "seccion": [
                    {
                        "titulo": "Balones de baloncesto",
                        "descripcion": "Balones para entrenamiento y juego.",
                        "imagen": "balon-baloncesto.jpg",
                        "alt": "Balón de baloncesto",
                        "url": "#",
                    },
                    {
                        "titulo": "Zapatillas de baloncesto",
                        "descripcion": "Calzado deportivo para jugar y entrenar.",
                        "imagen": "zapatillas-basket.jpg",
                        "alt": "Zapatillas de baloncesto",
                        "url": "#",
                    },
                ],
                "calendario": [],
                "resultados": [],
                "clasificacion": [],
                "historial": [],
                "temporadas": [],
                "puntos": [],
                "palmares": [],
                "sistema_ligas": [],
            },
            "publicidad": {
                "seccion": False,
                "calendario": False,
                "resultados": False,
                "clasificacion": False,
                "historial": False,
                "temporadas": False,
                "puntos": False,
                "palmares": False,
                "sistema_ligas": False,
            },
            "patrocinador": {
                "seccion": None,
                "calendario": None,
                "resultados": None,
                "clasificacion": None,
                "historial": None,
                "temporadas": None,
                "puntos": None,
                "palmares": None,
                "sistema_ligas": None,
            },
        },
    "salvador_fem": {
            "amazon": {
                "seccion": [
                    {
                        "titulo": "Balones de baloncesto",
                        "descripcion": "Balones para entrenamiento y juego.",
                        "imagen": "balon-baloncesto.jpg",
                        "alt": "Balón de baloncesto",
                        "url": "#",
                    },
                    {
                        "titulo": "Zapatillas de baloncesto",
                        "descripcion": "Calzado deportivo para jugar y entrenar.",
                        "imagen": "zapatillas-basket.jpg",
                        "alt": "Zapatillas de baloncesto",
                        "url": "#",
                    },
                ],
                "calendario": [],
                "resultados": [],
                "clasificacion": [],
                "historial": [],
                "temporadas": [],
                "puntos": [],
                "palmares": [],
                "sistema_ligas": [],
            },
            "publicidad": {
                "seccion": False,
                "calendario": False,
                "resultados": False,
                "clasificacion": False,
                "historial": False,
                "temporadas": False,
                "puntos": False,
                "palmares": False,
                "sistema_ligas": False,
            },
            "patrocinador": {
                "seccion": None,
                "calendario": None,
                "resultados": None,
                "clasificacion": None,
                "historial": None,
                "temporadas": None,
                "puntos": None,
                "palmares": None,
                "sistema_ligas": None,
            },
        },
    "vcv": {
        "amazon": {
            "seccion": [
                {
                    "titulo": "Balones de baloncesto",
                    "descripcion": "Balones para entrenamiento y juego.",
                    "imagen": "balon-baloncesto.jpg",
                    "alt": "Balón de baloncesto",
                    "url": "#",
                },
                {
                    "titulo": "Zapatillas de baloncesto",
                    "descripcion": "Calzado deportivo para jugar y entrenar.",
                    "imagen": "zapatillas-basket.jpg",
                    "alt": "Zapatillas de baloncesto",
                    "url": "#",
                },
            ],
            "calendario": [],
            "resultados": [],
            "clasificacion": [],
            "historial": [],
            "temporadas": [],
            "puntos": [],
            "palmares": [],
            "sistema_ligas": [],
        },
        "publicidad": {
            "seccion": False,
            "calendario": False,
            "resultados": False,
            "clasificacion": False,
            "historial": False,
            "temporadas": False,
            "puntos": False,
            "palmares": False,
            "sistema_ligas": False,
        },
        "patrocinador": {
            "seccion": None,
            "calendario": None,
            "resultados": None,
            "clasificacion": None,
            "historial": None,
            "temporadas": None,
            "puntos": None,
            "palmares": None,
            "sistema_ligas": None,
        },
    },
    "san_jose": {
            "amazon": {
                "seccion": [
                    {
                        "titulo": "Balones de baloncesto",
                        "descripcion": "Balones para entrenamiento y juego.",
                        "imagen": "balon-baloncesto.jpg",
                        "alt": "Balón de baloncesto",
                        "url": "#",
                    },
                    {
                        "titulo": "Zapatillas de baloncesto",
                        "descripcion": "Calzado deportivo para jugar y entrenar.",
                        "imagen": "zapatillas-basket.jpg",
                        "alt": "Zapatillas de baloncesto",
                        "url": "#",
                    },
                ],
                "calendario": [],
                "resultados": [],
                "clasificacion": [],
                "historial": [],
                "temporadas": [],
                "puntos": [],
                "palmares": [],
                "sistema_ligas": [],
            },
            "publicidad": {
                "seccion": False,
                "calendario": False,
                "resultados": False,
                "clasificacion": False,
                "historial": False,
                "temporadas": False,
                "puntos": False,
                "palmares": False,
                "sistema_ligas": False,
            },
            "patrocinador": {
                "seccion": None,
                "calendario": None,
                "resultados": None,
                "clasificacion": None,
                "historial": None,
                "temporadas": None,
                "puntos": None,
                "palmares": None,
                "sistema_ligas": None,
            },
        },
}